### ISSUE TITLE
overview of collection managers requirements for agents and related fields

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#103]
Collection Managers had a very useful discussion today about agents. I believe that this provides some useful information for moving forward, and will help clarify details related to several other 'agent' issues. Other agent issues are 
#98 #97 #93 #83 #65 #57 #15
I will leave it to WP3 to determine which tickets make sense to leave open, or perhaps be replaced/informed by this one.

We identified several "types" of agents, and made the analogy that each 'agent' would have a "contact card" full of data fields relevant to the agent.
- **individuals**; among other things would support aliases, contact information, birthdate/deathdate, and support many-to-one relationships with "where (and when) they collected" (eg. Brazil from 1990-2000 and Portugal 2001-2020) as well as professional affiliations (eg. AAFC from 2004-2020 and Harvard University from 1990-2000)
        - @rintoult has also identified that multiple addresses may be required, as she is sometimes required to send specimens to inspection stations as interim destinations when sending specimens to partners/clients.

- **groups**; this type of 'agent' would include a list of 'individual' agents. Queries on an individual, would also result in records where an individual agent was listed within a group. 
         - all collections agree that groups do not change members, if there is a difference, it is a different 'group'
         - at least one collection (DAO) also adds that the ORDER of members added to a group is a vital piece of information, so even if group had the same members, if they are listed in a different order, it is a different group. - this did not seem to be any issue for other collections, so it seems that enforcing 'order' will not cause any conflicts in use
         - we did not discuss 'names' of groups, but would value WP3 insight on what questions need to be answered regarding this
         - for data export, all group members should be listed as individuals (not the group name), though I think some sort of structured concatenation would likely be appropriate, would have to confirm based on further discussion and WP3 input.
 
- **organizations/expeditions** (name tbd) - this type of "agent" would be a name of an organization or expedition in which all participating people may be included in a description but would NOT be linked/identified to the record as individuals. The people are considered to be participants of the expedition, but not specifically the agent responsible for [eg. collecting the specimen]

- **staff/users** - we weren't sure how these are the same or different from other agents. In some cases staff will also be collectors/determiners. Staff will definitely be associated with specimen workflows (eg. DNA analyses) and there is the requirement to be able to maintain data regarding staff "agents" eg. when did they work with which collection and in what capacity (this may also be a many-to-one (student 1999-2001 and technician 2003-2005)). we would not want to manage data on individuals in more than one 'place'.

- **Taxon authors** - these are not agents acting on a specimen record, but relate to taxonomy, but are also people. In many cases, more than one author is part of the listed "taxon author" for a species. In many cases, "individuals" may also be taxon authors, and links between an individual (eg. a researcher) and the taxonomy/specimens they have described is useful. @shannonasencio and @dshorthouse are the most relevant folks to discuss this use-case with.

- using structured agent fields meets requirements of all collections. We are imagining that functionality would be along the lines of an agent field, that someone starts typing in (last name/group name/org name???) which then results in an autocomplete/search/picklist (to discuss further) to select appropriate agent, effectively linking to that agent entity/'contact card'

- the understanding is that changes made to an agent's "contact card" would be reflected on all records connected to it (true?/false?). 

- aliases; I _think_ that every 'alias' would be individual 'agents' that could be affiliated to each other? You would require a search on any variant to return results on all. BUT (depending on functionality), it (likely?) makes sense that more than one 'individual'. cannot have the same alias (eg. P. Catling cannot be an alias of Paul AND Pauline Catling, because you don't know which is relevant). Further discussion may be relevant, based on back-end functionality

- CNC has also identified the requirement of a verbatim text field for capturing related data as it appears on a label, which is not directly connected to an "agent". Ideally, an autocomplete on this field (based on other entries in the same field) is wanted. As CNC data is not currently using structured fields for their agents, steps will be needed in data migration to ensure agent data ends up in the relevant fields.

happy to discuss, or gather further info

**Comment by dshorthouse** [comment]
@heathercole Thanks for this. I don't see anything here that differs from other discussions on other tickets except perhaps some needed precision on what is an Agent, what is an agent string (= verbatim), where are aliases stored, and what is the interplay among all of these things, especially as they relate to the context in which they are used. We'll get the clarity we seek in upcoming adjustments to the user interface.

**Comment by heathercole** [comment]
@dshorthouse I don't understand what you are describing. The paragraph you quoted is not intended to have any relationship to the verbatim text string field, which is additional/separate requirement from CNC. Most collections would enter data into a structured field (as described) with direct connection to the agent being linked/associated to the record (similar to how an agent is selected from a list in the current implementation of the media module)

In the case of the CNC requirement for a verbatim text string field, it doesn't directly link to any agent data. CNC has indicated that auto-complete based on entries previously added to that same 'verbatim text string field' would be the preference. It does not relate to how the other collections would use structured agent fields. CNC is well-aware of the potential for mistakes, it exists everywhere; they have identified this as the field and function relevant.

In the case of CNC data, it seems likely that in the short term, that verbatim text field will have to be used to populate/represent relevant 'agent' (eg. collector) fields for data exports. If there are solutions to better relate/link the data, that would be worth investigating.

**Comment by dshorthouse** [comment]
@heathercole We may have crossed paths on an edit I just made to my comment. Might make more sense now with the new bits I added & I recommend a re-read. The key to all of this is context & the additional notion that People entries in the Agent module are unique – the best approximations of unitary identity as we can muster.

**Comment by shannonasencio** [comment]
"at least one collection (DAO) also adds that the ORDER of members added to a group is a vital piece of information, so even if group had the same members, if they are listed in a different order, it is a different group. "

The same applies to DAOM.

WRT taxon authors, agent records must have a field for author name (e.g. Alphonse de Candolle's agent record would have "A. DC." in the author field). When adding agents to a taxonomy record, the person entering the taxonomy record would need to specify the author role (e.g. author, ex author, parenthetical author). Parenthetical authors and ex authors precede authors.

In the example of _Aeschynanthus acuminatus_ var. _chinensis_ (Gardner & Champ.) C.B. Clarke, the author entries would be as follows:
-Gardner (= Gardner, George): role is parenthetical author, and needs to be attached first to the taxonomy record to maintain order (i.e. system needs to maintain order of authors added to ensure proper taxon name display).
-Champ. (= Champion, John George): role is parenthetical author, and needs to be attached second to the taxonomy record to maintain order.
-C.B. Clarke (= Clarke, Charles Baron): role is author.

In the example of _Acalypha commersoniana_ var. _parvifolia_ Baill. ex Müll. Arg., the author entries would be as follows:
-Baill. (= Baillon, Henri Ernest): role is ex author.
-Müll. Arg. (= Müller Argoviensis, Johannes): role is author.

**Comment by cgendreau** [comment]
Done with the support of aliases, orcid and wikidata

**Comment by heathercole** [comment]
would be great to have a demo of how all the different use-cases described above are implemented. For example, how will a group of people (eg. collectors) work in a way that can be re-used? I don't see how a group can be added in the current test-system.

**Comment by heathercole** [comment]
This functionality is not clear for collectors and determiners. If there is a group of people, it is not feasible to have to re-enter each member of a group each time the group is on a label or bulk-import. I don't see notes in #65 that indicate that CMs agree to 'abandon' the requirement for groups which is included in this issue.

in #65 
_"please note that there are other collections that are relevant to this requirement, and their input needs to be reviewed/incorporated also. "_

Please review that the proposed WP3 approach meets requirements for all the collection managers for all the types of agents outlined above for both manual and bulk-import of data.
@shannonasencio @OwenLonsdale  @michellelocke  @rintoult  @banchinic  @ron-reade
