### ISSUE TITLE
Associate permits with sampling/collecting event

### ISSUE THREAD

**Issue by jmacklin** [AAFC-BICoE/dina-planning#106]
GIVEN I have accessed DINA as collection manager

WHEN I take a sample/specimen(s) from a location that required a permit(s)

THEN I need to be able to associate the permit(s) with the sample/specimen(s) for reference (e.g. transactions)

**Comment by jmacklin** [comment]
From @rintoult 

Not sure this is the right place to put this comment but! I was just reviewing some of the standards associated with culture collections and realised it has not yet been mentioned that collecting event would have associated permits and documents that help with legalities of tissue. From this website: http://www.wfcc.info/index.php/guidelines/

image

**Comment by cgendreau** [comment]
You can already attach a document to a collecting-event. An import permit is a document where you can have a different sub-type.

**Comment by jmacklin** [comment]
Yes, true. Wanted to make sure this was tracked as a distinct use case that needs a sub-type(s) as you indicated. But, I think there may also be "flags" and metadata associated with the document to provide context. CMs can consider and comment.

**Comment by rintoult** [comment]
I just played with the attachments to a collecting event - how come I have to bring them from outside instead of picking them from the object store?

**Comment by cgendreau** [comment]
The attachment section is the object-store. But indeed it seems you can't select an existing one.

**Comment by cgendreau** [comment]
It is now possible to attach an existing object.

**Comment by OwenLonsdale** [comment]
A consideration, given that in the CNC, batches of specimens from the same collection event may be processed separately by the same or another person days or years apart. Should we ensure that the link to the permit remains attached to all new specimens records if that record is duplicated from an old one, or if it is generated from a cache of "collection events" (sensu the CNC DB)? This will ensure that all later records will be attached to the permit, and not risk disassociating the link, knowing that later people will probably forget (or not bother) to link the permit, or not know that the permit is there to be linked. OR, should we leave the linking responsibility to all later record creators?

**Comment by jmacklin** [comment]
@cgendreau can you confirm that if a permit is attached for a given collecting event it will be associated to all samples/specimens collected under that event?

**Comment by cgendreau** [comment]
yes, as long as it's the same collecting-event the permit will follow.

**Comment by shannonasencio** [comment]
There seems to be a bug here. I have played around with attaching/detaching several files (both pdfs and image files). At present, there is only one attachment to the collection event I created, but the system indicates there are two files attached ("Attachments (2)"). 

This has raised another question: do records have unique system-generated numbers for tracking purposes? I don't know how to communicate which record I am referring to other than "the collection event I created". I'm sure you've thought of this, but if not, it is critical that each record have its own unique identifier within the system.

**Comment by rintoult** [comment]
@shannonasencio you can include the weblink in your comment - they should be able to check it out that way I think at least for the testing database.

**Comment by cgendreau** [comment]
https://github.com/AAFC-BICoE/dina-planning/blob/master/docs/UserManual.md#identifiers

**Comment by cgendreau** [comment]
I will explain what happened with the attachments during the call since it will be easier. We will create a ticket to display deleted object since the issue here is simply that one attached object got deleted. Don't worry, they are "soft" delete and I will explain how you will be notified in the future.

**Comment by shannonasencio** [comment]
Sounds great! Thanks @cgendreau.

**Comment by michellelocke** [comment]
It would seem to make more sense to attach the permit inside the editing page, rather than to a saved record. I was creating a new collecting event and wondered why I couldn't attach a permit. It wasn't time I saved the collecting event that I realized that I could then attach the permit. It would be a more logical workflow to attach it in the editing page.

**Comment by dshorthouse** [comment]
@michellelocke Or both/either interfaces.

**Comment by cgendreau** [comment]
I will close this ticket and create a new one to allow attach object even before saving.
