### ISSUE TITLE
Record verbatim collecting locality

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#107]
Background: #19 

First iteration includes:

- verbatimLocality
- verbatimCoordinates
- verbatimLatitude
- verbatimLongitude
- verbatimCoordinateSystem
- verbatimSRS
- verbatimElevation
- verbatimDepth

**Comment by heathercole** [comment]
there is lots of related feedback in issue #66 
comments to collection managers: 

1. do you need 5 fields 
verbatimCoordinates
verbatimLatitude
verbatimLongitude
verbatimCoordinateSystem
verbatimSRS

for describing verbatim coordinates? In this case, there is often only 1 verbatim field for this data, then structured fields for latitude/longitudes (eg. where  (one of several) specific formats are required (and hopefully conversions possible)

I think it is clear that verbatim locality/elevation/depth are relevant.

**Comment by cgendreau** [comment]
Consider UTM coordinates:

verbatimCoordinates: 17N 630084 4833438
verbatimCoordinateSystem: UTM
verbatimSRS: EPSG:2029

**Comment by jmacklin** [comment]
I am sure UTM coords should be essential. From what I know, Canada used UTM as a standard for quite a while, especially out West. Some may even still be using it...

**Comment by heathercole** [comment]
totally agree, just asking whether there is a requirement for them to each have their own fields, or be captured in one verbatim field altogether.

We have to remember that many (most) people doing data entry are not researchers/technicians/ or even biologists and training for data entry is extensive. There are many fields that need a lot of training, it may be that managers consider it more effective to have all the coordinate related verbatim fields captured in one place. There is a lot of variety on specimen labels that can create confusion, if everything is together, then it reduces errors. Similar to one verbatim field for collectors/agents that gets parsed LATER by more knowledgeable user.

I don't know all the manager use-cases, but think it makes sense to review and not use fields that won't be practical for them to use. Or maybe you just put all the fields in, and let them use them however they want and hide the ones they don't want to see. That can work, and creates space for later.

**Comment by cgendreau** [comment]
Closing since all fields are there, changes should go in a new ticket. We will just add tooltips (with DarwinCore definitions) to help users.
