### ISSUE TITLE
Restrict Managed Attributes to Collection Manager

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#11]
Can be viewed by all users but add/remove/edit should be restricted to the Collection Manager (and Admin) role.

**Comment by Jkeyuk** [comment]
I was able to test this and verify it was working on the deployment server.

I was denied access to create/update/delete manage attributes until I was given access as a collection manager.

**Comment by shannonasencio** [comment]
It would be good to confirm with the individuals in the sprint group who are NOT collection managers (CM) that they are restricted from adding/removing/editing (I cannot test this because I have CM privileges).

**Comment by cgendreau** [comment]
We have test accounts that can be provided to test the different privileges.
