### ISSUE TITLE
Display caption under images in gallery view

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#111]
Based on feedback from #69, the gallery view should display Caption instead of filename (if the Caption field contains something). When a new file is uploaded, the Caption field will now include the filename by default but can be changed by the user.

**Comment by heathercole** [comment]
to me it seems like the only current way to edit the field when uploading or editing is completely manually. Will it be possible to declare select an existing field to be displayed? or even a build of existing fields?

A manual approach will work for some managers who won't use the feature regularly, but I think the CNC use-case may require something with more function. Will leave to @michellelocke to further review.

**Comment by cgendreau** [comment]
build of existing fields: yes, it will be done in #69
