### ISSUE TITLE
Add verbatim collector's number to collecting event

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#112]
GIVEN I have accessed DINA as a data entry volunteer

WHEN I add a new collecting event

THEN I expect to add a verbatim collector's number

AND then see it recorded.

Aside: a collector's number is common in botany, but does not represent a number for a person. Rather, it is self-assigned by the collector and is typically an incrementing alpha-numeric token that a collector etches on his/her pressed specimen sheets that indicates a run of specimens throughout a collecting season or lifetime. The home for this in Darwin Core is http://rs.tdwg.org/dwc/terms/recordNumber. As such every specimen in botany typically has a single collecting event.

**Comment by shannonasencio** [comment]
David has done a good job of summarizing the issue. Like all data entered, we need to be able to query on collector number. I have attached three screenshots to demonstrate how collector numbers may be displayed on labels (numbers are circled).

![CollNumber_01](https://user-images.githubusercontent.com/72618784/106495109-42444680-6489-11eb-9809-34fff753c71f.jpg)
![CollNumber_02](https://user-images.githubusercontent.com/72618784/106495119-46706400-6489-11eb-99de-3659ae1bc5b0.jpg)
![CollNumber_03](https://user-images.githubusercontent.com/72618784/106495146-4d977200-6489-11eb-9084-823ec1d0291f.jpg)

**Comment by dshorthouse** [comment]
Thanks @shannonasencio. Though subtle, I like the use of the possessive, `collector's number` as in _their_ number, not a number that purports to represent them as a person much like an ORCID ID might. Though we can infer identity in a portion of that string of alpha numeric characters (sometimes), it's not foolproof. For example, that last example "80-79" likely says: "Collector 80's 79th specimen" and so you can go searching for where is 80-78 or 80-80.

**Comment by shannonasencio** [comment]
@dshorthouse You are correct that "collector number" can lead to confusion. I actually typically call it "collection number".

**Comment by jmacklin** [comment]
I think there may be a need for 3 verbatim fields related to assignment of identifiers for an event. At the highest level there may be a "site number/identifier" that could be relevant to many collection kinds. This is closely tied to the event and is quite common from collecting trips that were logged like expeditions or surveys. The important point here is that it is not unique to the specimen as it indicates all specimens collected during an event. The next level of specificity would be the "collection number", which again would be relevant to many collection kinds. This "identifier" would typically be unique to a specimen (but not always) and may or may not be associated to a collector. I think your first label illustrates this as there is no direct indication that 3841 is associated with the collector. It could just be the specimen number associated with a particular day's collecting by a number of different individuals. The most specific identifier would be the collector number where it is "obvious" that the number belongs to a series related to the collector. Interestingly, the first label could be interpreted to have a collector number of 1945, but this may also be the date...? Collector numbers are very common in Botany/Mycology but not used as often in Zoology in my experience. If we are trying to keep things simple, we could combine the last two into just "collection number" and concatenate the various numbers/identifiers but this may lead to future confusion if it is parsed and would be more difficult to search on...

**Comment by heathercole** [comment]
I am not sure if it is clear whether the current implementation of this identifier is associated to the collection object record vs. the collecting event. Does this current implementation support one-to-one as well as one-to-many relationships between event and collector's number? In botany the relationship is typically one-to-one, whereas entomology is usually many-to-one and would have a different identifier to represent the collecting event. It also isn't clear (yet) how the "collection event" record data relates to the "collection object/specimen" record.
In DINA can you have an collection event without an collection object? or a collection object without an "event" (a collected object would certainly have some sort of actual 'event' associated to it, just not clear how these relate in the DINA schema).

**Comment by cgendreau** [comment]
> In DINA can you have an collection event without an collection object? 
yes, but it is usually temporary

> collection object without an "event"
No, this is not possible. There is always an event but it could be unknown. In such case we would have a placeholder event.

But the focus here is on collecting-event. It is simply the collector's number for the collecting-event. It doesn't prevent us from having a collector's number on collection object later but we are not there yet.

**Comment by michellelocke** [comment]
Collector's Number is not something used in entomology, so we have no comment on it's use.

**Comment by heathercole** [comment]
for botany, the collector number is associated to the collection object, which is often a one-to-one relationship with collection event. You could not have a collector number for an event without the associated object.

**Comment by shannonasencio** [comment]
@heathercole There are cases where there could be a collection event without an associated object. One example would be the field book entries that are often done as part of a rapid data entry workflow. Everything in a collector's field book would be catalogued and the records would be temporary in nature as @cgendreau suggests. It is possible that not every single entry from the field book would have a corresponding specimen housed in the collection, thus the unattached collection events would eventually be purged from the system.

**Comment by cgendreau** [comment]
After the meeting, it was decided to expand collector's number to a "list".

**Comment by cgendreau** [comment]
The work will continue on #136
