### ISSUE TITLE
Add autocomplete to verbatim collector field in Collecting Event

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#113]
GIVEN I have accessed DINA as a data entry volunteer

WHEN I begin typing in the verbatim collector field for a collecting event

THEN I expect to see this autocomplete to facilitate data entry based on all prior entries of verbatim collectors in other collecting events

AND if possible, all links to People in the Agents module become pre-populated for me based on what was linked in prior collecting events that had this exact same verbatim collector field

**Comment by cgendreau** [comment]
Users identified potential risk associated to the fact that you could, by mistake, re-use a verbatim value with a typo. The autocomplete will remain for now and could be removed or improved later. Possible improvement: add the number of "occurrence" of the verbatim string next to the value.

- C. Gendreau (18)
- C. Genreau (1)
