### ISSUE TITLE
Add ability to re-order linked Agents (= People) in a Collecting Event

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#114]
GIVEN I have accessed DINA as a data curator

WHEN I link 2+ people from Agent to a collecting event

THEN I expect to be able to re-order the linked people to visually correspond to the implicit ordering in the verbatim collector field

AND that when there is evidently 2+ candidate people in verbatim collector but only some are known Agent(s) that can be linked, I should be able to additionally indicate, perhaps through drag-drop reordering in what position are the known linked Agent(s) with a visual gap for the unknown.

![Slide1](https://user-images.githubusercontent.com/326459/106640661-50ab6480-6554-11eb-8fa7-343beef53437.png)

**Comment by cgendreau** [comment]
Re-ordering is fine but I'm not that convinced with the blank placeholder. I'm pretty sure sometimes we can't tell how many agents there are when the string is too long (et al.).

**Comment by dshorthouse** [comment]
Definitely true that we can't deduce identity in all instances (eg `Mrs. Smith Grade 4 class`) but in cases like the above, it's self-evident. I suppose the underlying question is, do we care about precision in ordering (or ordering at all)? What value does it bring to the collecting event or any of the specimen records that might eventually be linked to it? Dunno. I guess it depends how it is you store ordering in relation to the linked Agent. If it's not appreciably different to store and then render a blank, then meh. But, if this drag/drop js library is presently incapable of accommodating a blank then it may not be worth the effort.

**Comment by jmacklin** [comment]
I think there needs to be strong use cases that back up the need for structuring agents beyond verbatim. We definitely need to be able to search for agents for many reasons. @cgendreau how powerful are the parsing and text string index algorithms to allow for the verbatim fields to be searched? I would think they are pretty reasonable... They are used by some on the raw OCR label data to allow the blob to be searched. If this was reasonable and we could use facets with a "fuzziness" or soundex then this may be enough for the purpose...?

However, especially in botany there may be stronger need to associate the primary collector with a number/identifier that can be searched on. But, even this can be complicated in legacy as it may not be obvious whose number it is or whether it is associated with a group or not, etc. It does seem a little crazy to me that there is a need to separate each agent in a group (especially in the sense of the amount of time it takes to do the capturing of these asserted agents...). Perhaps as a middle ground we could just provide one structured agent field for the primary collector and an association to a number/identifier when relevant...?

**Comment by cgendreau** [comment]
The search on verbatim will be as good as the data but it will do a decent job.

**Comment by dshorthouse** [comment]
> I think there needs to be strong use cases that back up the need for structuring agents beyond verbatim.

That's a loaded statement & needs a bit of precision. What I *think* you mean here is `agent string` whole or extracted/parsed from verbatim as opposed to `Agent` the entity with an identifier.

The gradient between search (= don't mind ALL the dirt) vs find (show me *the* thing I want) is a tricky balance to strike, especially when we might also throw-in known aliases from Agent into a BLAST-like, expanded search. Again, clarity of presentation is important. Searching on an `agent string` is one thing but search on people is very different.

**Comment by jmacklin** [comment]
Yes, agree with your interpretation of my "loaded statement" ;-)

I think we need to have a discussion with the focus group to drill down on the use cases and priorities as some of this functionality may not be required nor in scope for release 2. This functionality will also have relevance to the search module and web presence and should be considered in that context as well.

**Comment by dshorthouse** [comment]
Insofar as "searching for a person in Agent to link to a Collecting Event" is concerned, little bits of context (= fields) drawn from Agent entries are critical to feed the search results. Here's one way to do it. Something for the future.

<img width="436" alt="Screen Shot 2021-02-02 at 2 56 21 PM" src="https://user-images.githubusercontent.com/326459/106655042-d9cb9700-6566-11eb-949b-177f83137910.png">

**Comment by cgendreau** [comment]
The re-order portion is done. The rest of the ticket can remain as reference for later but I would consider this ticket ready for validation.

**Comment by heathercole** [comment]
I think it worth consulting the collection managers, the herbaria have strong requirements for not editing/re-ordering collectors on a record. Not clear where this functionality falls in relation to having agent groups.

**Comment by dshorthouse** [comment]
@heathercole The work in relation to this ticket has all but eliminated the need for groups as a tool to facilitate data entry has it not? There's a fundamental difference between Agent (= People) Groups and agent **string** groups. The former are unique, disambiguated/unambiguous entries with the eventual intent of also having external identifiers whereas the latter are verbatim, possibly ambiguous entries _as written on a label_.

**Comment by heathercole** [comment]
@dshorthouse I don't think that the collection managers have been provided an opportunity to test how this works in an environment that reflects their actual workflow, relating to data entry, edits and exports. So I don't think it is appropriate to assume that this reflects all requirements. With the current in-development status of the system, it isn't obvious how these interact. To my knowledge, the managers were NOT consulted as to whether the structure you describe fulfills their requirements for this data.

**Comment by dshorthouse** [comment]
@heathercole This is why we have deployments and expected user testing of these prior to sprint meetings. The solution built here is only tangentially related to workflows, a mere taste of what these might be while we focus now on the core of what is a Collecting Event.

**Comment by cgendreau** [comment]
Closing, we can now re-order linked Agents.
