### ISSUE TITLE
Structured Start Event DateTime should not be a required field for Collecting Event

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#116]
As in the subject. Start Event DateTime appears to be a required field and a new Collecting Event cannot be created unless this field has content. In instances where Verbatim Event DateTime is purposefully unstructured (eg `Summer`), a structured Start Event DateTime cannot always be added.

<img width="487" alt="Screen Shot 2021-02-09 at 10 43 23 AM" src="https://user-images.githubusercontent.com/326459/107388292-ae473000-6ac3-11eb-8d86-02a2430bb6c6.png">

**Comment by cgendreau** [comment]
Fixed
