### ISSUE TITLE
error banner in add agent window

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#117]
not clear what I was doing wrong, name too long? spaces? email that exists already?

![add person error](https://user-images.githubusercontent.com/50373105/107652980-23933c00-6c4f-11eb-85e4-63f804d7534f.png)

**Comment by cgendreau** [comment]
yes, not pretty indeed: the error is "person_unique_email".

More work will be done to improve that so that we can display a better error message.

**Comment by heathercole** [comment]
@cgendreau will multiple log-ons be permitted by the same user (eg. with an AAFC LAN account, I can be logged into it on several machines at the same time), but in Specify, I can't, have to kick myself out if I try to log onto another machine. I [had] to create myself as a second user to use the system effectively for management. Eg. HAC1 logged in and doing changes that are 'processing forever', HAC2 logged in cleaning up data records at the same time......

Not sure how the new system will work, but would be great to think about this..... (what if I put a fake email in....)

**Comment by cgendreau** [comment]
But this is the agent windows, it does not represent your user used to login.
