### ISSUE TITLE
Fev 11 Demo Visual and experience improvements

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#119]
- The system should no save when the Enter key is pressed on a page
- Spacing between agents in collecting-event detail view should be fixed
- It should not be possible to save a Collector without a verbatim value

**Comment by cgendreau** [comment]
Save on Enter key is actually a normal behaviour that should be preserved for accessibility.

**Comment by dshorthouse** [comment]
> * It should not be possible to save a Collector without a verbatim value

Not sure about this. Are there never any circumstances where a collector is unrecorded but later inferred through other evidence such as examination of hand writing or acquisition documents?

**Comment by cgendreau** [comment]
It's a note from a previous meeting but I was also not sure about it. I think that argument is good enough to justify that not do that. I will close that ticket now.
