### ISSUE TITLE
Allow edits of object Rights section

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#12]
Defaults values should remain but it should be possible to change the values in the Edit View and on the upload page.

- Rights Statement
- Reuse Rights Statement (License)

https://github.com/DINA-Web/object-store-specs/issues/6

**Comment by shannonasencio** [comment]
I am not presented with an option to edit data in these fields in either edit view or on the upload page.

**Comment by cgendreau** [comment]
You can change the License which is the Reuse Rights Statement but indeed Rights Statement is currently missing. I will create a new ticket.

**Comment by hacole01** [comment]
this section needs to have options to represent media that is held by AAFC but does not belong to AAFC, and therefore we have no license/rights/copyright relevant for any sharing.

**Comment by hacole01** [comment]
- Seems like work-in-progress, but may be relevant to have ‘publicly releasable’ default = yes for images, and no for other types (eg. docs). Can this be bulk-edited?

**Comment by cgendreau** [comment]
The section already has options to represent media held by AAFC but doesn't belong to AAFC. The license shall be in the suggested list (otherwise it would mean you can't even use it, legally speaking) and the Rights Statement will be set the the original holder of the copyrights.

**Comment by cgendreau** [comment]
Yes the publicly releasable is indeed work in progress since it is captured but not used (and always false).

**Comment by hacole01** [comment]
> The section already has options to represent media held by AAFC but doesn't belong to AAFC. The license shall be in the suggested list (otherwise it would mean you can't even use it, legally speaking) and the Rights Statement will be set the the original holder of the copyrights.

I don't currently see a license option which allows a user to indicate there is no appropriate license (eg. AAFC not Rights Owner)
![DINA license options](https://user-images.githubusercontent.com/50373105/98710059-2ed58380-2351-11eb-832f-a18c130597f4.png)

**Comment by cgendreau** [comment]
Yes, that's the original goal of that ticket but it won't be a Licence optional since they are 2 distinct things. If someone gives you a picture, they will keep their copyright (Rights Statement) but it will also have a licence that allows you to use the image. The list is configurable but I'm not sure you should accept images outside of that list since we are creating derivatives.
