### ISSUE TITLE
Allow to easily add symbols for degree, minute, second

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#120]
GIVEN I have accessed DINA as a dina user

WHEN I need to enter verbatim values that include symbols like degree, minute, second : `°` `'` `''`

THEN the system allows me to use a button (or equivalent) to add the value to a text box so it is not necessary to type it

cc @michellelocke

**Comment by dshorthouse** [comment]
Might I also suggest a keyboard shortcut for these w/ tooltip on the symbols?

**Comment by heathercole** [comment]
another shortcut that may be relevant later is the × (alt 0215) for hybrids (not an 'x')

**Comment by cgendreau** [comment]
Symbols issue fixed in https://github.com/AAFC-BICoE/dina-planning/issues/125
