### ISSUE TITLE
Record georeference data

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#122]
GIVEN I have accessed DINA as a dina user

WHEN I need to add a georeference assertion to a collecting event

THEN the system allows me to add a georeference assertion and all the related data (see mockup)

AND I should be able to add a georeference assertion even if there is already one on the collecting-event

A georeference assertion is structured data that represents a specific point (with uncertainty and could also be a shape) on the planet

**Comment by cgendreau** [comment]
![georeferencing_mockup_20210217](https://user-images.githubusercontent.com/1470054/108220769-179ef280-7105-11eb-97f1-85eaa3fb7bd0.png)

cc @TravisGobeil

**Comment by gobeilt** [comment]
This is what I am using as my schema/wireframe for Location thus far. It includes Verbatim fields as well as Asserted Georeferencing fields. It does not include Geography (Political) 

![Locality-SoFar](https://user-images.githubusercontent.com/77449369/108769753-698db100-7527-11eb-93fa-f4b177b6f1b1.png)

**Comment by heathercole** [comment]
These look great! would be good to think about options for hiding fields that may not be used, and having fields that are often used located together. Not clear on the requirement for Ver. Coord AND ver lat/long AND structured lat/long? When mapping becomes possible, which fields are structured? If it is that lat/long field in the georeferencing 'box', perhaps these should be located elsewhere. As a user, inputting lat/long from a label, all those 'other' fields in the georeferencing box may not be relevant. But I think much of this depends on implementation of ongoing feedback from the CMs. :)

**Comment by gobeilt** [comment]
> would be good to think about options for hiding fields that may not be used

100% We're going to come up with a way for Collection Managers or maybe even Users to hide irrelevant fields. These initial iterations will always show everything, so everyone can see the full schema. Just know that it's a future feature in the plan. 

> Not clear on the requirement for Ver. Coord AND ver lat/long AND structured lat/long?

It's kind of either or, but it only works one direction. I can enter a Verbatim entry that then gets translated over (either manually or automagically) to the Georeferencing (assertion) data. Or I can just enter Assertion Data if there is no Verbatim on the label. I would NOT allow you to enter Geo Assertions and then make that the Verbatim Entry. That we should not allow.

**Comment by heathercole** [comment]
to clarify, we should verify that at least one CM will use each field, but separately have option to minimize fields/boxes that are seldom used). Not sure we use "hide" the same way :)

So, would a data-entry workflow go along the lines of :
1. " ooo, my label has some coordinates, I can recognize lat/long, so I enter them in the verb lat and verb long box and then click a button, those are copied to the verb. coordinates text field AND the structured lat/long fields?"

and
2. (scenario above), but there are also some notes about the coordinates that I don't understand, so I can add them to the verb. coord field.....

vs. 
3. I am editing a record, there are no coordinates, so I am using the fields in the georeferencing 'box'... data entry is fun!

----
if those scenarios are [realistic], then perhaps the structured lat/long could be visible elsewhere, as scenario 1 and 2 (I think) don't use the georeferencing box fields.

**Comment by michellelocke** [comment]
I think that we are more likely to use verbatim lat/lon, as that is the type of data we will most likely have. Verbatim coordinates, as Heather worked out in scenarios 2, would be for a different coordinate system where you could not figure out lat/lon. Not often used but important to be able to capture that data. We would use it rarely but it would still be needed sometimes.

**Comment by cgendreau** [comment]
The 3 scenarios that @heathercole mentioned should all be supported. The key concept is that you always have at least 1 verbatim value (in any of the Location related fields) and then you add a georeference assertion.

**Comment by dshorthouse** [comment]
I see a drop-down for `Verification Status` with an option shown, `Requires Verification`. I suspect this represents running thoughts, but if this were implemented, how/who does the verifying and where/how is the result of the verification stored? Can more than one person verify? Is the verification stateful? Does the georeference data become locked once verified?

**Comment by dshorthouse** [comment]
Should `Georeferenced By` have an additional link to a Person in Agents?

**Comment by cgendreau** [comment]
I would say that they should have their own tickets since they will bring more discussion.

**Comment by jmacklin** [comment]
If the verbatim coords are in degrees or UTM will we support and automated conversion to decimal degrees as an assertion of a georeference? We will need the decimal degree conversion for the mapping service.

**Comment by jmacklin** [comment]
Where would a verbatim uncertainty be captured if this information is given on a label? Likewise, there may be information about a protocol, source or remarks.

This begs the question as to whether the collector who did provide a georeference for the event is also making an assertion that is recorded in the structured fields? And if they are not, but we need the georeference data to appear in the structured fields so we have a standardized form to promote searching and use of the mapping service, etc., is that transfer (hopefully at least semi-automated) then an assertion by the person doing the data capture...?

**Comment by cgendreau** [comment]
> If the verbatim coords are in degrees or UTM will we support and automated conversion to decimal degrees
No not short term, it requires some tools that we don't have. Unless there is an external service doing it.

> 
This begs the question as to whether the collector who did provide a georeference for the event is also making an assertion that is recorded in the structured fields?
To me that's a yes. It's an assertion based on an instrument. There is indeed no place for verbatim uncertainty. Do we need one? Probably if the value is often provided. If we target instruments we probably want something like `verbatimCoordinatePrecision` but it gets tricky since the value expected would be in degree, not meters.

**Comment by michellelocke** [comment]
You currently have to save twice to save the Assertation, once by hitting the Save GeoReference Assertation button and second by hitting the Save button for the whole record. If you don't do both of these saves then the assertation is not saved. This seems redundant to have to save it twice. I would prefer to save it with all of the other data, just by saving the record (no separate save Assertation button). When you edit a record that should give you the power to edit and save everything, no extra steps needed to add or save info. It's frustrating to have to save multiple times and will definitely lead to people forgetting and having their data lost, having to repeat the process.

**Comment by michellelocke** [comment]
When I add a georeferenced Date to the assertation it seems to always add in a time, without me having asked it to. 

Example: I added the date 2021-03-01. The data I see now is 2021-03-01T05:00:00Z. Hopefully this will be fixed. If I add a past date I don't want it adding an assumed time. This is false data.

**Comment by TravisGobeil** [comment]
Agreed, @michellelocke . You cannot have a Save within a Save like this. Ever. It's bad UX. 

The first assertion should always saved along with everything else in the Collecting Event record. This is the standard user experience that all record collecting should uphold. Save the data. HOWEVER, if you need a second (or more) assertions on top, only then should you engage additional UI to do so. And you should NEVER have to Save within a Save. Nested Saving is the worst kind of Dark UX Pattern. 

> **Golden Rule of UX:** Only make me do something when I divert from the norm.

### UX Journey: Adding a secondary Georeference Assertion:

1. There should be a button that says "Add Another Georeference" or "Additional Georeference"
2. Once clicked, you then see the second assertion in a tab. Add your data. 
3. That's it! Save your record. You do not need to 'Save' the secondary assertion. 

Repeat: You do not need to independently 'Save' any data on this screen. It should all be saved together at the same time.

**Comment by michellelocke** [comment]
@TravisGobeil Even though I knew I had to save twice I just forgot while creating a new collecting event and was extremely frustrated that I had to go back to add the data again! Please fix this!

**Comment by michellelocke** [comment]
Can the Georeference Sources be a pick list? I think that most of the time we are going to be using a limited number of sources (Google Maps, GeoLocate, etc.) This will help eliminate spelling mistakes with users entering these sources over and over again.

**Comment by cgendreau** [comment]
Please note that the issue will be closed today since it was about the initial work. All issues/improvements should have their own issues to not mix up all the topics in a giant ticket.

**Comment by OwenLonsdale** [comment]
Can we allow the georeferencing field to understand multiple forms of lat/long? For example, decimal format AND hours/min/sec, etc? It's a useful feature in the CNC DB. 
If we have access to the coordinates in hours/min/sec and we know that it is accurate, I would like to be able to copy & paste that into the georeferencing field.

**Comment by cgendreau** [comment]
georeferencing itself is only in decimal degrees but something will be added to move it from verbatim where it could be in degree/min/sec.
