### ISSUE TITLE
Collecting Event: second symbol in DDMMSS is generated as two single primes as opposed to a double prime

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#125]
The character submitted through alt-3 generates two single prime characters rather than a single double prime character.

**Comment by cgendreau** [comment]
We will use symbols from https://en.wikipedia.org/wiki/Prime_(symbol)

**Comment by TravisGobeil** [comment]
On a Mac it is actually ridiculously easy to type these special characters : 

° Degree: Option-Shift-8 
‘ Prime: Option-]
“ Double Prime: Option-[

(_The [ and ] brackets are next to the P key. The dashes indicate you should hold these keys at the same time, starting with the one on the left_)

#### Simplest Solution:
Anyone doing data entry on a Mac can learn these special key bindings as easily as any other. But how much simpler could we make them ourselves? Simply have a **tooltip for Mac users**, and we can **implement special key bindings for PC users**. Just disable them on Mac. Educate the user either way. 

#### For reference and clarification :
U+2032 ′ PRIME (HTML `&#8242;` · `&prime;`)
U+2033 ″ DOUBLE PRIME (HTML `&#8243;` · `&Prime;`)
U+00B0 ° DEGREE SIGN (HTML `&#176;` · `&deg;`)

**Comment by cgendreau** [comment]
The bug is fixed, shortcuts on Mac issue should have its own issue.

**Comment by dshorthouse** [comment]
Ticket for Mac bug #133
