### ISSUE TITLE
Add support for agent person aliases

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#131]
GIVEN I have accessed DINA as dina user

WHEN I need to add an alias to a person

THEN the system allows me to add it to the person record (a person can have more than 1 alias)

AND the system allows me to specify the language of the name if the information is available

**Comment by dshorthouse** [comment]
Did you mean to write, "More than one entry at a time if necessary?"

**Comment by cgendreau** [comment]
not really, just that you can enter more than 1 alias, at any time.

**Comment by cgendreau** [comment]
I guess language would use codes from: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
I'm wondering if actually we don't want the script: https://en.wikipedia.org/wiki/ISO_15924

The main issue is that nobody will really know that without searching.

**Comment by dshorthouse** [comment]
What if as a first pass we forego any language and just have a bag of names as say 3 input boxes by default but UI to add more as needed.

**Comment by TravisGobeil** [comment]
I suggest we have a text box, with one alias per line. Here is an example wireframe showing before and after filling it out: 

![Agent-New-WithAlias1](https://user-images.githubusercontent.com/4238302/109074034-2d905280-76c5-11eb-8a32-4438d3b2948e.png)

### View Agent Page: 
Showing aliases as filled out (we can pretty up how they are spaced out but the | pipe is probably the best to keep it clean)

![Agent-View](https://user-images.githubusercontent.com/4238302/109074064-3c770500-76c5-11eb-9769-7f8de81454e4.png)

**Comment by dshorthouse** [comment]
@TravisGobeil I like it! Uncluttered and simple. Bit of caution with the implicit linebreaks for the textarea though – we're likely to receive content that's not nicely \n\r, especially with data migrated from sources. But, easy enough to tidy when/if encountered. The next big ticket is using the aliases in search when linking verbatim to Person in eg `Collected By`.

And, this for @cgendreau, if you're fishing for some elasticsearch examples that mirrors this almost exactly wrt to model and search, respectively:

https://github.com/bionomia/bionomia/blob/master/lib/elastic_user.rb
https://github.com/bionomia/bionomia/blob/master/helpers/query_helper.rb#L8

**Comment by cgendreau** [comment]
Just to clarify, linebreaks are for display purpose only, they are not preserved. It's the same thing that we are currently using in managed attributes. All trailing endlines that is sent to the API will be removed but, if you have one in the middle of the string it will take it. We can simply sanitize all of that for all the fields here since it doesn't make sense in the other fields (except maybe note).

**Comment by michellelocke** [comment]
I have added aliases to some of the agent records and it works well.
