### ISSUE TITLE
Collecting Event: DDMMSS shortcut keys for symbols generate spurious characters on a Mac

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#133]
Using Brave Version 1.20.108 Chromium: 88.0.4324.182 (Official Build) (x86_64) as well as Firefox 86.0 on macOS Big Sur, the alt-1, alt-2, alt-3 shortcut keys (option-1, option-2, option-3) conflict with OS/Browser actions and produce additional, spurious characters seen below.
<img width="332" alt="Screen Shot 2021-02-25 at 10 56 17 AM" src="https://user-images.githubusercontent.com/326459/109180067-82c97400-7758-11eb-9d53-10b71ff826f2.png">

**Comment by cgendreau** [comment]
What about an approach like GitHub when you type ":" in the comment box ? It shows a dropdown, you pick what you want or you continue to type to ignore.

**Comment by TravisGobeil** [comment]
I suggest a character you wouldn't normally use - such as the tilde ~ or maybe #hashtag

**Comment by cgendreau** [comment]
Since cross platform shortcuts were getting tricky, there is now buttons at the end of the appropriate fields.
