### ISSUE TITLE
Collection Event: Can these be shared between multiple collections?

### ISSUE THREAD

**Issue by rintoult** [AAFC-BICoE/dina-planning#134]
I think I have brought up this question in discussions before. 

But I would like to know.

Will collection events be shareable between collections? DAOM and DAOMC have many specimens derived from the same collection event. Will we be able to link to the same event or will each need to be duplicated?

I can ask this in the meeting later today if that is easier. 

@shannonasencio @cgendreau @ssbilkhu

**Comment by cgendreau** [comment]
That should possible. Not saying there is no challenges but it should be possible.

**Comment by cgendreau** [comment]
Done
