### ISSUE TITLE
Collector's number should not be split by comma

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#136]
comma is a character that could be used in a collector`s number so it should not be used as separator.

**Comment by dshorthouse** [comment]
@shannonasencio Also suggested that there's a need to differentiate what *kinds* of numbers might be in the list. One might the primary collector's number and other numbers might be different (or unknown/unknowable).

**Comment by cgendreau** [comment]
What would be the name of the other numbers? `Other Collector's Number`?

**Comment by dshorthouse** [comment]
> What would be the name of the other numbers? `Other Collector's Number`?

@shannonasencio? I didn't catch a suggested label for the dirty bucket.

**Comment by shannonasencio** [comment]
"Other collection numbers" or "Other numbers associated with the collection". They are not necessarily all collectors' numbers.

**Comment by cgendreau** [comment]
Are they assigned in the fields or in the collection? Collector's number is in collecting-event since it was assigned during the event but if it's in the collection we will record it later (later in the process in the sense at the "specimen" level).

**Comment by dshorthouse** [comment]
Thanks, @shannonasencio. So, does that mean a single, definitive `Collector's Number` field as we once had with no separator and then an additional set of fields (or multi-entry) to capture the `Collection Numbers` dirty bucket? I suppose the latter *could* contain what might be a collector's number with the `Collector's Number` remaining blank if there's every any uncertainty in what the number actually is.

**Comment by shannonasencio** [comment]
@cgendreau These are collection event-level numbers, not other numbers like accession #, etc. that are assigned by collections staff. 

@dshorthouse Yes, let's keep that single Collector's Number field with no separator, and then also have multi-entry collection numbers. 

Thanks to you both!

**Comment by dshorthouse** [comment]
Bingo! Thanks @shannonasencio!

**Comment by cgendreau** [comment]
I would like to add a tooltip on `Collection Numbers` to avoid confusion. Suggestion?

**Comment by jmacklin** [comment]
How about something simple like:
"Other numbers or identifiers associated with the **collecting event** that help to distinguish it. Do **NOT** include specimen-based identifiers such as accession numbers"

**Comment by shannonasencio** [comment]
I like James's description, but I would be even more specific: "Other numbers or identifiers associated with the collecting event that distinguish it from other collecting events. Do NOT include specimen-based identifiers such as accession or catalogue numbers."
