### ISSUE TITLE
Agent: Saving aliases throws error

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#137]
<img width="369" alt="Screen Shot 2021-03-03 at 10 08 20 AM" src="https://user-images.githubusercontent.com/326459/109826186-8b162900-7c08-11eb-908f-035d90816ef3.png">

**Comment by cgendreau** [comment]
agent is running on the old version: moduleVersion "0.9", we will deploy the latest now.

**Comment by cgendreau** [comment]
fixed
