### ISSUE TITLE
warning page regarding "the information you're about to submit is not secure"

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#139]
Using Chrome, on my windows desktop, onsite in Saunders at AAFC, I was logging into DINA by clicking the 'AAFC login' on the jump page.

After that, I got this notification. I clicked 'send anyway' and got to DINA, but I think that we would want that to generally NOT happen. Especially odd, as I am onsite.
![dina not secure](https://user-images.githubusercontent.com/50373105/110003100-0ef11380-7ce4-11eb-8447-00d106362610.png)

**Comment by cgendreau** [comment]
This a sandbox environment without proper certificates. It will change at some point but for now this server is only used to validate requirements.

**Comment by heathercole** [comment]
i didn't recall seeing it before, cheers.
