### ISSUE TITLE
Remove Save GeoReference Assertion

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#140]
original report: https://github.com/AAFC-BICoE/dina-planning/issues/122#issuecomment-790807510

cc @michellelocke

**Comment by dshorthouse** [comment]
And as enhancement, tie the global save for the Collecting Event to cascade a save for all assertions.

**Comment by cgendreau** [comment]
Yes, I was not suggesting to not save the assertions.

**Comment by TravisGobeil** [comment]
Yes. **One save to save them all**, and in the database...bind them?

**Comment by cgendreau** [comment]
I would keep it at the Save, implementation details are not out-of-scope here.

**Comment by heathercole** [comment]
I tried to add a georeference assertion with bad lat/long (6876/123567), then I selected to add another georeference assertion, then I realized I didn't want to add another one, so I tried to save the record and this happened: 

![georeference error](https://user-images.githubusercontent.com/50373105/110831661-72d98600-8268-11eb-94e1-020873e6a776.png)

when I removed the lat/long, I could save the record, it kept the assertion (had a person entered), and did NOT keep the 2nd (empty) one that I made.

I think it is great that there is a check on the lat/long format, however, it would be more useful if the field changed colour or something so indicate there is an issue, either when the data is entered, or perhaps when you leave the field to the next one.

**Comment by heathercole** [comment]
Question to managers; should you be able to save an assertion with no lat/long data? What if you tried to georeference a record and it wasn't possible? I would propose that you can only save an assertion WITHOUT a lat/long if there is text in the remarks field (which likely be explaining why a lat/long not possible?)

Would you want the system to let you save with no lat/long AND no remark, would you want an error/alert in that case?

**Comment by michellelocke** [comment]
I would like some kind of check box or tag that says _Georeferencing Failed_ for ones where nothing could be obtained. This way others know it's been tried and unsuccessful and others do not waster efforts to continually try.

CNC has "Geocoding Failed" Keyword that records can be tagged with. DINA will need to accommodate this somehow.

I would not want to save an assertation with no data. Perhaps if there was a checkbox for Georeferencing Failed in the assertation then it could be saved with that box checked and no other data or a remark as well.

**Comment by cgendreau** [comment]
yes that was discussed. Could you create a ticket for it so it doesn't get lost please ?

**Comment by cgendreau** [comment]
Issue related to coordinates now here: #152
