### ISSUE TITLE
Collecting Event Georeference: Show all georeferencing fields for a new assertion without me having to click a button

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#143]
GIVEN I have accessed DINA as a georeferencer / collection manager (whatever)

WHEN I add or edit a collecting event that does not yet have any georeferencing information

THEN I should not have to click a button to create a new georeferencing assertion. The fields should already be visible to me.

**Comment by cgendreau** [comment]
>  If coordinates are provided on the label, do managers want/need to enter this as a separate assertion
yes, they are different things. We will add some tools to copy the values (including degree/minute/seconds)

**Comment by heathercole** [comment]
would want to have verbatim coordinates from label represented in the structured lat/long, perhaps without additional need for assertion than 'from specimen label' (or something)

**Comment by dshorthouse** [comment]
See #151
