### ISSUE TITLE
navigating away (without saving) saved edit of collection event

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#146]
I was testing the behaviour of the collection event record. Specifically, I opened a record, then deleted the (exsiting) georeference assertion.

Then I navigated out of the page by selecting from the top menu.

When I went back to the record, the assertion was not there. I think this is a problem for several reasons
- many people think that navigating away would cancel (not save) the changes
- there should be a 'you didn't save, are you sure you want to leave here' prompt, which allows you to either leave without saving, or save, or return to the record

Note, I tried this by doing an edit to collectors (removed a collector name), then navigated away without saving. When I returned, the edit was NOT still there. Similarly, ADDING a georeference and navigating away without saving also resulted in the georeference NOT being kept.

**Comment by cgendreau** [comment]
Fixed
