### ISSUE TITLE
requirement to communicate 'georeference not possible'

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#148]
GIVEN I have accessed DINA as user

WHEN I am georeferencing specimens and there is a record where a georeference is NOT possible

THEN there should be a checkbox (or similar) to indicate this

AND the geoference would be saved with no lat/long.

from #140

**Comment by heathercole** [comment]
I did some research regarding the terms "geocoding" vs. "georeferencing". In some cases, they are used interchangeably, and in others they have specific definitions that do not completely overlap. It does seem that the global collections community (including GBIF) most commonly use the term 'georeferencing', so I suggest that DINA continues with that as well. 

Regarding terminology for the ticket, depending on the source of the georeferencing attempt, it may be relevant to be able to distinguish between a user effort (eg. "georeference not possible") vs. an automated/system attempt (eg. "georeferencing failed")

**Comment by cgendreau** [comment]
We have a glossary: https://github.com/AAFC-BICoE/dina-planning/blob/master/docs/glossary.md#georeferencing

**Comment by cgendreau** [comment]
`georeference not possible` will be moved into georeferencing assertion so er can record a date, an agent and a remark.
