### ISSUE TITLE
Agent quick data entry

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#15]
When the user uploads objects, new agents could be required to be created. It should be possible to create them without leaving the current view.

**Comment by cgendreau** [comment]
This is also mitigation for #7

**Comment by Jkeyuk** [comment]
I was able to verify this is working on the deployment server through the use of the 'add new person' button.

**Comment by hacole01** [comment]
I tried using the 'add person' butting adding a test person with a made-up email. I did not subsequently find them available in the document creator or upload by lists

**Comment by PoffM** [comment]
If there are enough Person records in the database then the dropdown won't show all records, and you would need to type part of the name into the spreadsheet cell to search for the Person. If this is the issue then we would need to have the UI clarify that.

**Comment by cgendreau** [comment]
Closing since this feature will be changed to another implementation.
