### ISSUE TITLE
Collecting Event: Add a button that allows me to copy verbatim georeferencing info. into a new assertion

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#151]
GIVEN I have accessed DINA as data manager

WHEN I add verbatim coordinates as seen on a physical label attached to the specimen

THEN I want a button that copies these values into a new assertion

The verbatim coords might be expressed in DDMMSS & I'd want these to appear as auto-converted DD in the assertion.

**Comment by cgendreau** [comment]
overlaps with #147 but we will use this one.
