### ISSUE TITLE
Add validation on decimal lat long

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#152]
GIVEN I have accessed DINA as a dina user

WHEN I enter invalid coordinates

THEN the system warns me and doesn't save it

**Comment by dshorthouse** [comment]
Assuming valid means:

- latitude -90 < y  < 90
- longitude -180 < x < 180
- all values present
- all numerical

But could it mean a warning if:

- any value 0
- too many significant digits

**Comment by cgendreau** [comment]
only that for now:
latitude -90 < y < 90
longitude -180 < x < 180

When PostGIS will be available it will be expanded.
