### ISSUE TITLE
Record the date of the collecting event

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#17]
DINA User Story: https://github.com/DINA-Web/dina-model-concepts/issues/13

**Comment by dshorthouse** [comment]
"Date" here ought to be plural to accommodate a range of dates with a start and end datetime. However, part of this requirements must also accommodate freeform entry of human-readable dates such as `Summer 1999`.

**Comment by cgendreau** [comment]
Indeed verbatim date(s) should be captured.
