### ISSUE TITLE
Collecting Events: Checking georeferencing not possible should not flush content in form fields prior to saving

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#171]
GIVEN I have accessed DINA as user

WHEN I check "Georeferencing Not Possible" in a Collecting Event when there is existing content in the form fields that would ordinarily be rendered disabled

THEN that existing content should not be cleared out in the UI when the checkbox is clicked. It should merely be made disabled. When I then uncheck the checkbox without saving the form, I expect the original content to remain in the form fields.

**Comment by cgendreau** [comment]
What if the content is hidden but comes back if you uncheck it?

**Comment by dshorthouse** [comment]
@cgendreau That'd be fine provided the user has not suffered from cardiac arrest in the interim.

**Comment by cgendreau** [comment]
There is also the option to simply not show the checkbox unless there is nothing in the assertion. Not sure there is a valid reason to wipe data to say can not be georeferenced. So if there is data and you need to express "can't be georeferenced" you clear it or you create a new assertion.
