### ISSUE TITLE
Material Sample: Create many child Material Samples from a single parent

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#173]
GIVEN I have accessed DINA as a user

WHEN I create a Material Sample

THEN I should be able to create 'n' Material Samples and then presented with a view to see all of them

**************************
Additionally, when I later (or concurrently) wish to attach a Collecting Event, then only the root Material Sample can receive an attached Collecting Event and I should not be able to attach a Collecting Event to any of the children.

**Comment by cgendreau** [comment]
Done
