### ISSUE TITLE
Collection Manager requirements for "identification" related data fields

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#179]
GIVEN I have accessed DINA as [all users]

WHEN [i need to add (or query) identifications relating to a specimen]

THEN [the system must be able to hold (and display) multiple identifications]

AND [support required flags/tags relating to taxonomy/type status]

AND identify which is current, or which may represent storage location

See more info below

**Comment by heathercole** [comment]
The collection managers discussed this requirement and identified a few different types of "Annotations" that relate to the specimen record. In this issue, we are defining an "identification" as a particular type of annotation which includes a taxonomic determination. I will also separately document other annotations (without taxonomic determinations in an issue HERE (placeholder)

Data fields for “Identification” = a taxonomic determination
- taxonomic name (must connect to a manageable taxonomy resource; more info to come on this soon)
            - qualifier (eg. cf. or aff.)
           - addendum (eg. sensu lato/stricto)
- type status (eg. pick list)
- identified by (determiner) (link to agents)
- date identified (to confirm that verbatim and structured date fields are required)
- identification remarks (text field)

When there is more than 1 identification
- identify which is current (eg. check-box)
- identify which it is filed as/stored as (may not be filed under current name)
- (clarify if any other info is needed related to multiple dets per specimen)

Users entering identifications should be able to add new taxonomy (also relates to taxonomy resources). For CNC there must be a flag of some kind to identify newly-added taxons for review, after which the flag can be cleared (by user with appropriate permissions)

When development begins, we should review together if there is a requirement for data fields relating to:
- verification status: categorical indicator of whether the identification is correct (use controlled vocab/picklist)
- identification references
- other

*in some cases, identifications may relate to sequence data/files and not an accessioned specimen/record.

**Comment by shannonasencio** [comment]
A quick note regarding qualifiers - they can occur at various levels within the taxonomic hierarchy (e.g. _Russula silvicola_ s.s.; _Smilax_ cf. _tamnoides_)

**Comment by heathercole** [comment]
> Data fields for “Identification” = a taxonomic determination
> 
> * taxonomic name (must connect to a manageable taxonomy resource; more info to come on this soon)

NOTE: not all collections may want a direct link to the taxonomy resource, for some collections a text field or pick-list from taxonomy list may be relevant.

Will need to be discussed.

**Comment by cgendreau** [comment]
All done expect "filed as" that is now tracked in #227
