### ISSUE TITLE
Collection Manager requirements for 'other' annotations

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#180]
GIVEN I have accessed DINA as user

WHEN I want to record information/observations about the specimen

THEN there need to be data fields to record the information

AND include who made/added the observation/information and when

(more info below)

**Comment by heathercole** [comment]
For managing specimens and related information, the managers have identified the requirement to be able to add digital 'annotations' to the specimen record. 

For some collections, this includes the requirement for specific fields (Eg. measurements) with the capacity to include the date and person adding the information to the record.

Similar to the 'determination' requirements #179 , there may be many 'annotations' per specimen record. 

In some cases, these may be linked to 'processes' but the delineation here is not yet clear. In some cases it would be overly burdensome to have to declare 'i measured' as a process when entering a measurement.

Other management 'notes' may also be relevant here (eg. this specimen needs to be re-imaged), but they may not need similar structured info including agent/dates.

This requirement to be discussed further as development progresses.

**Comment by michellelocke** [comment]
To me, this seems to be a catch-all topic currently. If some kind of other annotation is something found regularly in the data then a field should be created for it (ex: measurements). If that needs to be something that is a Preparation Process to capture more info like who performed the process then that's what it should be. If we need to indicate a specimen needs to be reimaged then that specimen should be flagged (so a flag should be created that says "Reimage"). If we have something that does not fit in any field then there should be a general Notes field for the record to hold all of that info that we don't know what to do with or what it means.

I think this issue needs to be refined further. I'm quite unclear about what this is intended to capture. Fields that DINA does not yet handle?

**Comment by heathercole** [comment]
certainly a 'notes' or similar field is a good catch-all, the purpose of this type of structure would be when you want to have "who" and "when" as well as the 'note' captured in a structured way that could be searched on. 

I think there are many solutions possible when developers/users further define use-cases/requirements.

**Comment by cgendreau** [comment]
Done by combination of managed-attribute, remarks fields and tags.
