### ISSUE TITLE
data fields needed to describe storage location of objects/specimens

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#184]
** I will be more than happy to review/revise this requirement when it becomes relevant to WP3 **

Below is my request to CM's and their responses (these should be considered preliminary; not final responses)

Please list the data fields that you need to describe the storage information relating to your collection. Whenever possible, please briefly describe the type of data (eg. text fields, pick list, etc).

Additionally, describe any function/action that you need to be able to do. Eg. if you move several specimens to a new place, what would that look like? How would you need to update your records.

For some collections; this may be very straightforward; all flies are stored in "Diptera" organized taxonomically, so you wouldn't record a drawer or cabinet, so if they moved drawers/cabinets, you wouldn't update the data record.

For CCFC, perhaps there is detailed info about vials in positions, in holder-things, in particular cold-storage.... etc.

**Comment by heathercole** [comment]
**CNC and DAO**

Subcollection (e.g. type collection, general collection, exsiccatae): pick list
Physical location: text field

With regards to updating location, there should be a batch edit function that can be applied to any field in the CMS.

**Comment by heathercole** [comment]
**GINCO and CCFC**

For CCAMF we currently have the following data fields in SeqDB and I think they currently meet our needs:
-Container Name
-Room Number
-Storage Unit
-Compartment
-Shelf Number
-Rack Number

We sometimes need to move a bunch of stored soils or vials (50 to hundreds of samples) from one storage location to the other (one box to another one or move them from one fridge to another). That's why we need bulk edit and ideally a barcode gun! Each time I process a sample from the greenhouse it's location will also change from the greenhouse to the lab to a box once I've done the work and I put the sample in a ziploc bag for long time storage.

We have a lot of different storage types (greenhouse, stored soil samples box, -80 storage, etc...).

**Comment by heathercole** [comment]
**CNC**

We don't currently use storage location as a feature so I've got nothing to draw from. Heather's example of Diptera is pretty accurate for us, I think. We wouldn't want to record drawer or cabinet numbers because it would be so time consuming to have to change everything just because you had to add one new specimen which causes a cascade for three cabinets (I've done this)! We also periodically add in cabinets when we need space so having to insert one into the middle of the collection would be a pain.

I much prefer having a Collection/Unit (Diptera, Hymenoptera, Minor Orders, etc.) and Subcollection/Subunit type fields (Alcohol Collection, Slide Collection, Type Collection, Genitalia Cabinets, Freezer, etc.). This would be more practical if we choose to use storage fields as there would be much less "moving" of specimens in the database required. I also like Shannon's idea of a Physical Location text field. This way we could indicate more specific details as needed, for example: the exact freezer, room number, etc.

I am operating under the assumption that batch edit will be available for all fields in the database. This is a definite must have.

I can't think of anything else for now. We don't have the requirement of legally needing to know where anything is so our use case for storage is not as robust as some of the other collections.

**Comment by shannonasencio** [comment]
> **CNC and DAO**
> 
> Subcollection (e.g. type collection, general collection, exsiccatae): pick list
> Physical location: text field
> 
> With regards to updating location, there should be a batch edit function that can be applied to any field in the CMS.

**********************************************
@heathercole I believe the header here should be DAO and DAOM?

**Comment by cgendreau** [comment]
implemented
