### ISSUE TITLE
Material Sample: Preparation Substrate

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#192]
**WIP:** Discussion 2021-05-17 reached partial consensus that this term may be rejected in favour of a collapsing with #190 and #191 yet to be described.

GIVEN I have accessed DINA as a user

WHEN I access/edit a material sample

THEN I should be able to declare what is the substrate

Here, a preparation substrate is defined as the material on which the organism in the material sample is presented or grows.

Terms:

- rock
- log
- agar

**Comment by cgendreau** [comment]
I will close this ticket but `substrate` will be added as a field in collecting event (in another ticket)
