### ISSUE TITLE
Preparation Type should be per group

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#194]
Preparation Type view should allow to filter by group. It should also not be possible to edit the Preparation Type from another group.

**Comment by dshorthouse** [comment]
Are preparation types globally unique or unique to groups?

**Comment by cgendreau** [comment]
If you refer to the name of the PreparationType it is currently not unique. But they all have their own identity so there are technically unique.

**Comment by dshorthouse** [comment]
Thanks for this. So, if I understand correctly, a `PreparationType` in one group may have exactly the same human-readable name as used by another group but they are treated as different?

**Comment by cgendreau** [comment]
At the moment it can even have the same name in the same group. Not saying it makes sense but it is currently like that.

**Comment by jmacklin** [comment]
I really hope we can agree on a common vocab as much as possible for this term and others... Why do we think this needs to be by collection? Need to make sure there are good definitions. That is what is crucial.

**Comment by dshorthouse** [comment]
@jmacklin I'd assume that some collections will desire a breadth of types different from others & there's a desire for these to not pollute others' lists. It's a 6 of one 1/2 dozen of the other kind of scenario here I expect. Some types are obviously worth sharing, others not usefully so, especially if there might wind-up being many more in one collection than the others expected.

**Comment by cgendreau** [comment]
The glossary exists, we just need someone to submit a definition.

It is required by collection simply to make its usage simpler so you don't see PreparationType that are technically not possible for your collection. There is very little overlap between most of the collections. It doesn't prevent you from using a PreparationType from another collection.

**Comment by jmacklin** [comment]
I actually don't think there will be that many in the list but we shall see. What I am concerned about is that any overlap in Type makes use of the same label and definition. Otherwise we will lose some ability to query across collections for what types of preparations we have, which could be important to management (e.g., alcohol collections of varying kinds for OHS) and may complicate sharing in some cases (not apples to apples).

**Comment by cgendreau** [comment]
Then a person responsible for data sharing should be responsible for the maintenance of that.
