### ISSUE TITLE
must be able to identify more than 1 determination per "specimen" as "current"

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#195]
GIVEN I have accessed DINA as [all users] (eg. students doing data entry and managers curating data)

WHEN one specimen has more than one current determination (eg. when initially collected, material was thought to be all the same species, but was subsequently found to be more than 1 species (there can be many))

THEN we need to be able to identify that all "current" determinations are "current" (vs. a new determination that supercedes an older/legacy one)

AND when data is shared/exported all current determinations should be included.

*For many purposes, it is likely that only "current" determinations will be exported/shared (similar to georeferencing). With the legacy determinations maintained in the system, but only exported if there is a particular request. However, in the case described above, there needs to be the capacity to identify multiple "current" determinations associated to a single specimen/specimen identifier so that the relevant specimens/taxonomy are included in the export.

**Comment by dshorthouse** [comment]
@heathercole Would you mind please elaborating on what you mean here by "current"? I took this to mean _the_ most recent identification rather than adherence to a generally valid (or available) scientific name, but in re-reading what you wrote I am now unsure.

Recall that each Material Sample, including child samples, will have their own identifications and their own identification histories by design. We also intend to have these identifications nested under 1:many Organisms to accommodate multi-taxa scenarios per Material Sample. How these bubble-up (or not) to the parent Material Sample is presently unknown (it's a presentation issue more than a fundamental modelling issue), but there will nonetheless be expected use of the Darwin Care determination history extensions within which ALL identifications can be shared. This is particularly important for type specimens that may have since been re-identified but nonetheless continue to bear a published name that must be shared.

**Comment by heathercole** [comment]
Yes, by "current" I am trying to say the "most recent". BUT, in the cases where 2 different species are identified on the same sheet (when there was initially only thought to be one at the time of collection), then there would be a "current" determination for each different species. In this case the 2 (or more) different determinations are both linked to the same specimen identifier/on the same sheet, representing essentially an identifier for the "collection event". Current practices (with DAO) only apply separate identifiers in the case of different collection events which would be indicated by 1) different dates, 2) different locations or 3) different collector numbers.

**Comment by dshorthouse** [comment]
Thanks for the clarification. I now understand your "current" here to mean temporal recency & was not suggestive of taxonomic opinion nor recency of published treatment.

In biological reality, no material sample ever consists of a single organism even if it's an accessioned object consisting of a single leaf on a single sheet with a single administrative barcode. However in practical terms, I believe this statement here has your use-case covered:

> We also intend to have these identifications nested under 1:many Organisms to accommodate multi-taxa scenarios per Material Sample.

In your scenario, there would have once been a single `Organism` indicated in the `Material Sample` with its identification history, one entry most recent than others, notwithstanding how we record `dateIdentified` when none may exist. Later someone discovers another `Organism` affixed to the same sheet & perhaps also to the same specimen. So, you'd add another `Organism` to that `Material Sample`, another identification nested within it & now you'd have two most recent identifications for two different organisms on the same sheet & they share the same collecting event. This is functionally no different than an accessioned bit of tree bark with 3+ species of lichen. And by `Organism`, I'd expect there to be an optional `organismID` as accommodated in Darwin Core to track precisely the same individual entity (eg tree 52a from the arboretum) sampled from the field over time (2+ collecting events), though not germane to our scenario here.

**Comment by heathercole** [comment]
It will not always be relevant/possible to annotate the physical specimen with additional identifiers. Depending on how the schema is developed for data display and export, there may still be the requirement to associate 2 different "current identifications" to a single collection identifier/event which can be directly associated to the same (eg. sheet). I can see that the system may create a nested relationship, the data will have to work with they way the physical specimen is curated according to each collection.
@shannonasencio will be a good contact for this particular scenario and identifying the interaction between the data and physical specimen curation.

**Comment by heathercole** [comment]
This relates to the fields being noted as "primary". Just flagging this requirement, as it seems like something that is currently being worked on.
