### ISSUE TITLE
Remove Data when Removing a Managed Attribute

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#198]
Currently:

When a user currently removes a Managed Attribute they are warned:
Note: Removing an attribute from the 'Visible Managed Attributes' list doesn't delete the value. To delete the value, clear the input below.

Suggested Solution:

It would be preferred to actually delete the data after warning them when they remove the Attribute (not before): "Data will be deleted if you remove this Managed Attribute". I am removing the visibility because I no longer want that data.

**Comment by dshorthouse** [comment]
It would likely help the user if they could see how many records have used the value prior to deletion. There's a distinct difference between deleting something that's never been used (potentially no harm done) vs. deleting something that's been used 10k times. However, in the case of _eg_ the multimedia harvestor and perhaps other placeholder terms for eventual API calls in other modules that have managed attributes, deleting a value - even if presently unused - may unintentionally break future implementations in development.

**Comment by cgendreau** [comment]
This ticket is about managed attributes inside a CollectingEvent, not managed attributes themselves.
