### ISSUE TITLE
Add MaterialSampleType

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#199]
Not sure if this is decided but I'm assuming it would be required.

MaterialSampleType: whole organism, dissection ...

PreparationType: alcohol, sheet ...

MaterialSampleType would described what is prepared and the preparation type will be the state of the material sample ?

@dshorthouse

**Comment by dshorthouse** [comment]
Yep, we have to come to grips with the scope of either of these terms & we'll need to agree on what is the dividing line to make a useful distinction. Is one term about the organism represented (i.e. an expression of its physical features or state) & the other more about the non-biological medium in which the former is presented? Is one a superset of the other? We do not have a standard to fall-back on so it's up to all of to decide what this line is. In your example above, I suspect many of us at present would call a dissection a PreparationType. Instead, a PreparationType "dissection" would perhaps be best stated as being a "part of an organism" for its MaterialSampleType. And finally, does a PreparationType require specific human action, requiring that it have a PreparationProcess whereas a MaterialSampleType bears no such constraint?
