### ISSUE TITLE
Will we be able to copy/push data between groups?

### ISSUE THREAD

**Issue by rintoult** [AAFC-BICoE/dina-planning#201]
Question back to copies of same things - will there be an option to copy a "preparation type" from one group and save it to another. Or just generally will data be copyable- pushable from group to group?

This would be applicable to specimen records that have both herbarium and cultures, preparation types that are identical between groups, protocols. Collecting events etc.

Tara

**Comment by rintoult** [comment]
I tried to assign to Travis as well but couldn't find him?

**Comment by ssbilkhu** [comment]
> 
> 
> I tried to assign to Travis as well but couldn't find him?

I've added Travis to the dina-planning project, when he accepts the invite, i'll add him to the issue.

**Comment by cgendreau** [comment]
As a general rule I would say that data should not be copied unless it's a different thing. If you get a specimen from another collection that is in Dina you will work from that specimen, it should not be duplicated. You can always use data from other groups.
