### ISSUE TITLE
Create CCFC collection in test instance?

### ISSUE THREAD

**Issue by rintoult** [AAFC-BICoE/dina-planning#211]
Can an admin create a CCFC collection so that I can play with the new features? 

Tara

**Comment by cgendreau** [comment]
done

**Comment by rintoult** [comment]
Can you please add the DAOMC code - I don't seem to have access for editing - I am trying to create some sample records for sharing with others.

Thanks, 
Tara

**Comment by cgendreau** [comment]
fixed, I wasn't sure about the code

**Comment by rintoult** [comment]
Thanks,
