### ISSUE TITLE
Was all data just wiped from DINA?

### ISSUE THREAD

**Issue by rintoult** [AAFC-BICoE/dina-planning#217]
I created a whole bunch of records to use for screen shots - but now when I go in it seems there are no Material Samples?

Tara
![ms_dissappeared](https://user-images.githubusercontent.com/68067109/133659682-dafda3e9-552b-449d-86ed-b71fcb187a21.JPG)

**Comment by ssbilkhu** [comment]
Unfortunately yes, going forward we will re-configure the TEST server for more stability (as in not losing data after a crash) but this TEST environment maybe wiped clean on purpose in the future again.  This time it was unexpected.
