### ISSUE TITLE
Add object-store filters

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#22]
Missing filters reported by the user:

- Uploaded By, should be a dropdown list of agents and should support IS NOT
- Date Original Version Created: to allow search by photo “date taken”

**Comment by shannonasencio** [comment]
No option to select "Uploaded by", so cannot test. Was able to search on "Date Original Version Created" (great to be able to search on that criterion with date ranges!).

**Comment by cgendreau** [comment]
`Uploaded by` is now called `Metadata Created By`
