### ISSUE TITLE
Record MaterialSample filed as

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#227]
GIVEN I have accessed DINA as dina user

WHEN I need identify which name a specimen is filed as/stored as (may not be filed under current name)

THEN the system allows me to enter it even if the name is not in the list of Determination

**Comment by dshorthouse** [comment]
In what sections of the UI would/should "Filed As" appear, given this is neither pure Storage or pure Determinations?

**Comment by cgendreau** [comment]
It appears at Determinations level but it's not in Determination elements.
