### ISSUE TITLE
Managed Attributes description should be mandatory

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#23]
Mandatory description required for managed ‘attribute’ fields that  are created. A description should be provided in at least one of the supported languages.

**Comment by Jkeyuk** [comment]
I was able to verify on the deployment server that a description was mandatory to create a managed attribute.

**Comment by shannonasencio** [comment]
Did not work for me. When I tried save either with or without a description, I received an error message: "Access is denied: undefined". Type was set as "string".

![MA description_1](https://user-images.githubusercontent.com/72618784/98384147-696eb180-201b-11eb-8f1d-91ba95193438.png)
![MA description_2](https://user-images.githubusercontent.com/72618784/98384148-6a074800-201b-11eb-9214-2157240a0edf.png)

**Comment by cgendreau** [comment]
Your account was not set with collection-manager role. Should work now. I will create a new ticket to fix the error message.

**Comment by shannonasencio** [comment]
Working well now, thanks.

**Comment by hacole01** [comment]
collection managers should receive training and approval status for these. There is currently a managed attribute called "status" with a description "the status". This is not following best practices for Open Data.

Who is responsible for French translation? Perhaps creation of new managed attributes should need approval, and collection managers responsible for bi-lingual fields. This is very important for the sharing/export of fields, which all require bi-lingual meta-data.

**Comment by cgendreau** [comment]
The current data in the system represents test data therefore it can be anything. Approval and translation should be done outside DINA and coordinated among collection managers. Clarification: In most of the cases, I do not expect Manager Attributes to be shared. Once their usages is clear and stable, they are expected to be migrated to real attributes.
