### ISSUE TITLE
Add links between material samples and specify the nature of the relationship

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#231]
GIVEN I have accessed DINA as a user

WHEN I have a pair of material samples in the same or different collections

THEN I should be able to link them according to a specified relationship that may/may not be biological in nature

The above is primarily a placeholder to define what are the relationship types, how then can be defined for clarity in internal use and clarity in external use should they be shared.

One suggestion is to make use of the [OBO Relations Ontology](https://www.ebi.ac.uk/ols/ontologies/ro) such that the terms of the relationship have an external reference + definition & whose reciprocal arrangement can be specified/discovered.

Comments below should include URIs with their reciprocal terms we want to use to describe relationships

**Comment by dshorthouse** [comment]
has_host: http://purl.obolibrary.org/obo/RO_0002454
host_of: http://purl.obolibrary.org/obo/RO_0002453
 
parasite_of: http://purl.obolibrary.org/obo/RO_0002444
parasitized_by: http://purl.obolibrary.org/obo/RO_0002445

pollinates: http://purl.obolibrary.org/obo/RO_0002455
pollinated_by: http://purl.obolibrary.org/obo/RO_0002456

**Comment by cgendreau** [comment]
Done
