### ISSUE TITLE
View Collection Method description on list page

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#233]
I would like to be able to view the description of a Collection Method on the Collection Method list page. Users will need to see these notes and should not have to click on each individual Method to see the details. If I am in the English portal I should only see the English notes and French notes for the French Portal.

Along those lines, we do not need to see the Created By and Created On on the list page but do need to see it on each Collection Method record page.

**Comment by cgendreau** [comment]
Fixed
