### ISSUE TITLE
clarify use of custom 'managed attributes'

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#242]
The collection managers have spent a lot of time reviewing and documenting requirements for the data fields needed to appropriately capture and manage their collection's data.

Many of the required fields are not yet apparent in the DINA test instance, and WP3 seems to be indicating that many of them will be accounted for with the 'managed attributes' section.

Please provide a version of the current schema (eg. graphical or tabular) that can be reviewed by collection staff which identifies where all the fields required by collection managers will be included and clarify who will be responsible for ensuring all the required fields with associated formatting requirements (eg. text/picklist/lookups) will be added to the Collection management system.

**Comment by heathercole** [comment]
Hi David,
That is a very technical answer, with a VERY technical link. I am not trying review this: https://dina-web.github.io/collection-specs/#tag/Material-Sample 

Perhaps I didn't use the correct terminology. What I am asking for (doesn't have to be today), is an overview of the current data schema for the biology-data fields/tables in DINA that can be reviewed in non-technical terms, something like this
https://www.mantisbt.org/docs/master/en-US/Developers_Guide/html/images/erd.png 
or 
https://www.specifysoftware.org/specify-6-schema/

If that type of representation is available in the link above, please provide some instructions/context with how to view it more effectively.

Thanks!

**Comment by dshorthouse** [comment]
We held a DINA workshop at TDWG two weeks ago with data and collection managers in attendance where we introduced them to what OpenAPI is & what you can get from it. I'd be happy to repeat parts of it for the purposes of learning what are the core fields, their definitions, what are the managed attributes, how bits and pieces relate to one another & how this interface is useful for data managers in particular.

If I understand the motivations for this ticket, it's to learn **if** and **how** particular fields of data in the source map to particular fields in the destination. Such schema images don't permit those critical next steps & neither would collapsing them into a tabular view. What **does** is actually digging into the data migration process once development comes to a close. Might there be new proposed core fields revealed during migration? Perhaps.

**Comment by heathercole** [comment]
Hi,
Thanks for that info regarding the OpenAPI, it might be interesting to learn more about it. However, at the moment,  to clarify the request, it is a request for an overview of the current DINA data schema for the biology-data fields/tables in DINA that can be reviewed in non-technical terms, something like this
https://www.mantisbt.org/docs/master/en-US/Developers_Guide/html/images/erd.png
or
https://www.specifysoftware.org/specify-6-schema/

cheers!

**Comment by dshorthouse** [comment]
Heather - expand the POST requests in that OpenAPI interface. You'll see core fields like the below in a far less technical presentation imho than a schematic that does not lend well to next steps. I'll leave it to @cgendreau to respond about the feasibility of creating such a schematic, but my suspicion is that the backend of DINA does not lend itself well to such a traditional, technically dated ERD diagram due in large part to the storage mechanism of managed attributes.

<img width="742" alt="Screen Shot 2021-10-29 at 2 39 33 PM" src="https://user-images.githubusercontent.com/326459/139485909-d8f94f61-7ee4-4b8b-85da-769c9ece43b7.png">
.

**Comment by cgendreau** [comment]
The OpenAPI specification is the data schema.
