### ISSUE TITLE
Pick list values for Collecting Method are not constrained by Group

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#247]
As in the subject. Collecting Method values are created under the umbrella of a Group but the resultant list of options when creating a new Collecting Event are not constrained or filtered by that more limited list. In other words, all potential values for Collecting Method are displayed as options regardless of the Group under which the Collecting Event is created. A Collecting Method = "pitfall trap" is good for cnc but irrelevant for dao.

**Comment by cgendreau** [comment]
Done
