### ISSUE TITLE
Attchment thumbnails on Material Sample

### ISSUE THREAD

**Issue by rintoult** [AAFC-BICoE/dina-planning#249]
Are thumbnails supposed to display on the material sample pages when images are added as attachments? 

Ie my attempt here for a fungal toucan. 

http://onottra678350xl.agr.gc.ca/collection/material-sample/view?id=6e7ab24a-a49d-4416-be95-02752b857ee9

If not why not and can they? 

Tara

**Comment by banchinic** [comment]
I also need to have at the very least thumbnails of the images. Or even better, the full image showing. Also some arrows to toggle between the images because I add more than one image for each specimen.

**Comment by michellelocke** [comment]
Yes, this is a requirement for us was well. We must have thumbnails of images showing in the material sample.

See example in a CNCDB record: https://www.cnc.agr.gc.ca/taxonomy/Specimen.php?id=4658

**Comment by cgendreau** [comment]
Fixed
