### ISSUE TITLE
Sorting contents of a Storage Unit

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#254]
There is currently no way to sort the contents of a Storage Unit that are also Storage Units.

For example, For unit Diptera > cabinet cabinet 124, there is no way for me to sort the drawers within that cabinet (listed under Nested Storage Units). The contents (drawers) are listed in random order (or an order I cannot figure out):
drawer 4 - created 10-13
drawer 7 - created 11-05
drawer 6 - created 10-13
drawer 2 - created 10-13
drawer 1 - created 10-13

They are not listed in alphabetical/numerical order nor are they listed in an order in which they were created. I would want to see these in numerical order but there is no way to toggle the order.

If there are Material Samples in a Storage Unit (ex: as in drawer 2) you can sort those but cannot sort if the contents are another Storage Unit.

Please fix so that Storage Units within Storage Units can be sorted.

**Comment by cgendreau** [comment]
Fixed
