### ISSUE TITLE
Record collection object identifiers

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#26]
https://github.com/DINA-Web/dina-model-concepts/issues/21

**Comment by rintoult** [comment]
Is there a trick to adding Other IDs under the edit function on material samples? Not working for me this morning.  Also not working on "New" material sample.

**Comment by rintoult** [comment]
Also in the future will there be a separation of Collection Codes such as "DAOMC" from the catalogue number?  Our habits are to only work with the numbers in the identifier field - are they now going to be collated as a single entity?

**Comment by rintoult** [comment]
I encourage that definitions be attached to the fields in the future - these should be reviewed by the collection managers. I trust that will happen later.
