### ISSUE TITLE
Entering an incorrect date leads to false data

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#260]
If a user tries to enter an incorrect date in the date fields that have calendars built in (ex: Preparation Date, Georeferenced Date, etc.), there is no warning that the date is not valid and the field auto-populates with an incorrect date. This cannot happen as it leads to false data being inserted into the field. As the user is not notified, many users will not notice this mistake and will save the record with incorrect data.

Here are a few examples:
Entering 2021.2.29 - gives: 2021-03-01 - It cannot just change the date to the next available one. Funnily enough entering the date as 2021.02.29 gives you a completely different date of 2021-02-28.

Entering the date as 2021.v.3, valid in entomology circles but not accepted in this field. As such, it's likely users may try to enter dates this way. After hitting enter I get a date of 2021-01-01. I tried this with other dates and it seems that it keeps the year you enter but resets the month and day to January 1. This created an erroneous date.

Entering date as 21.6.18. gives a date of 2021-01-01. I've actually had that style of entry work a few times (ex: 89.6.14 gives 1989-06-14).

False data cannot be inserted and the database cannot automatically be changing invalid dates. The user must be flagged that their date is invalid and they must enter a valid date.

**Comment by cgendreau** [comment]
Fixed
