### ISSUE TITLE
Linked Agents fields difficult to find Add New Person

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#261]
In all of the linked Agents fields it is difficult to find the Add New Person option. 

Firstly, this field is at the bottom of the list. It's not a big deal to scroll down to find it now, but eventually this list could be populated with hundreds or thousands of people. Scrolling to the bottom of a list that long is time consuming and not practical.

Secondly, the Add option is only present when the entire list of people is selectable. When there are other values in the list the add option is present sometimes, and most times not. As soon as there are no matching values it says "No options" and you have no option to add a new person. Example: I want to find J. Richard Vockeroth. I type "v" and get only two results (none I'm looking for and no option to add new), I type "vo" and get "No options". The only way to add a new person is to delete what I have typed and scroll to the bottom of the original list. Typing the letters e, t or u gives you the option to add a new person, but the letters q, w, r or y do not. I don't know why this is so inconsistent but Add needs to be consistency an option.

Thirdly, You cannot start typing "add" to find it. There doesn't seem to be a way to search for this option in the list.

The user is left with no other option than to scroll to the bottom of the original list to find the add option. If the user starts typing, and gets no match, they must delete all they wrote (time consuming) then scroll to the bottom of the main list (also time consuming). Please fix all linked agents fields to that the Add New Person option is always available to the user in the list.

**Comment by dshorthouse** [comment]
I suspect a big part of this shortcoming is this temporary "search", which does little more than hit the back-end using traditional SQL & is hampered by its inability to tokenize what's typed. Search using the Elasticsearch appliance is under active development & somehow THAT will need to be wired-up here.

That said, #221 will come back to bite us if we're not careful with our expectations of what is an "Agent" (= Person) vs an agent string vs an alias and where/how disambiguation takes place.

**Comment by cgendreau** [comment]
Fixed
