### ISSUE TITLE
Catalog of Life does not show taxonomic hierarchy

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#268]
I have successfully returned a search result for the Determination Scientific Name (ex: Dasysyrphus limatus (Hine, 1922)). I then want to check to make sure I do indeed have the correct name. I click onto the name, which takes me to the Catalogue of Life record. That record does not show me the hierarchy of that taxon (ex: That it is in the Order Diptera, Family Syrphidae, etc.).

This is a huge problem. I would have hoped that part of the advantage to using a service like this would be a quick way to see the hierarchy to easily be able to determine if you have selected the correct name or not.

I can't even figure out a way to navigate anywhere to see the hierarchy on Catalogue of Life. 

The CNC DB is a little different in that you select the name and save the record first, but then you can navigate to the taxonomy database and you see the hierarchy. Even when you save your material sample, the link to the Scientific Name remains the same and no hierarchy can been seen. 

The must be fixed.

**Comment by dshorthouse** [comment]
We're presently evaluating an alternative service through Global Names that might afford a more streamlined experience. Indeed, separation between a scientific name on a det. as a nomenclatural statement of fact that most closely represents the intent of the determiner from its more fluid position as a concept in a hierarchy is a key tenet & driver.

**Comment by OwenLonsdale** [comment]
We will like whatever alternative nomenclature service you find as long as we can: 
-edit directly and easily;
-upload our existing framework to preserve the immense editing/updating/aggregating labour our taxonomic experts have done in the CNC taxonomy database over the last 10 years.

**Comment by cgendreau** [comment]
hierarchy is now displayed on selected names.
