### ISSUE TITLE
Cannot delete managed attribute in object store

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#269]
Despite permissions to do so, cannot delete a managed attributed in the object store.
<img width="486" alt="Screen Shot 2021-11-15 at 7 56 35 AM" src="https://user-images.githubusercontent.com/326459/141786023-cd83c033-56e7-40f1-a87a-432d5fc077b9.png">

**Comment by cgendreau** [comment]
Fixed (if the managed-attribute is not in use)
