### ISSUE TITLE
geography/location data fields

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#273]
When WP3 demo'd the functionality surrounding the geography/location lookup in DINA, several of us at the meeting expressed concerns with the data that was being pulled in from the lookup service. In some cases, it added artificial information to the record, and in some cases pulled in out of date information. 

At that time, several people offered to consult further as a working group for this. We expected WP3 to reach out to review requirements, and I have reached out on the subject several times via email. James indicated I should submit this as a ticket here.

There are also issues with how typos are handled, and questions about how queries and data-exports will work.

**Comment by cgendreau** [comment]
You can remove all artificial information. There is an X next to all levels (except country and province).

**Comment by cgendreau** [comment]
Typos remains in verbatim or you can create a Custom Place Name if you want with the Nearest Named Place.

Export will use Darwin Core `verbatimLocality`, `countryCode`, `stateProvince` and `locality` for now.

**Comment by heathercole** [comment]
That manual solution won't work, as the issue is that many users will not be able to identify whether information is artificial/incorrect/out-of-date. The system can't rely on individual/personalized user knowledge for verifying that, else significant amounts of artificial data may be introduced into records and collection's data. It would be much more reliable if only the country and province fields were populated, and available as discrete fields.

Current implementation around these fields does not meet requirements. There are issues surrounding this feature/functionality that need review/discussion with collection managers to review requirements.

**Comment by cgendreau** [comment]
> It would be much more reliable if only the country and province fields were populated, and available as discrete fields.
yes, and it's doing it :)

Please provide a concrete example of where the requirement is not met knowing that a manual solution is not optimal and can be improved.

**Comment by heathercole** [comment]
Current implementation around these fields does not meet requirements. There are issues surrounding this feature/functionality that need review/discussion with collection managers to review requirements.

**Comment by heathercole** [comment]
![image](https://user-images.githubusercontent.com/50373105/143060803-68a477f6-cbe3-4e02-a6a0-424d20da2fec.png)
County is wrong. Can't rely on user to know this and manually remove.

**Comment by cgendreau** [comment]
The second Ottawa is not really wrong since Ottawa is a single-tier municipality. To call it "county" is not accurate indeed.

The reality is that everything between the first level and province is not really relevant and if the user can't tell it can remains there or can be removed. 

Britannia Beach beach here gave you the exact polygon:
https://nominatim.openstreetmap.org/ui/search.html?q=Britannia+Beach

**Comment by heathercole** [comment]
"if the user can't tell it can remains there" is not acceptable as this creates a very significant risk of a large amount of artificial data being added to the record. It is not acceptable to rely individual/personalized user knowledge for verifying that data OR to require them to remove it manually.

The system has to enable quick and efficient entry of information from the collection label. Most users doing this work are students, it is not feasible to require them to have geographical knowledge or to review what data added by the lookup service may be incorrect or inappropriate to add to the label.

**Comment by cgendreau** [comment]
> is not acceptable as this creates a very significant risk of a large amount of artificial data 

That's a technical issue. I will take care of it thanks.

> The system has to enable quick and efficient entry of information from the collection label

It does it, that the purpose of verbatim fields

> not feasible to require them to have geographical knowledge or to review what data added by the lookup service may be incorrect or inappropriate to add to the label

that's the point of using a service, you don't need to know as long as the top place is accurate the rest is irrelevant.


What would you suggest to change, concretely, to change on the current solution ?

**Comment by heathercole** [comment]
feedback and requirements from CMs on this issue are extensively documented in GitHub #66 . Specific requirements for this functionality need to be further reviewed with CMs.

> that's the point of using a service, you don't need to know as long as the top place is accurate the rest is irrelevant.
Irrelevant data should not be added to the record 'by default'.

The current implementation would be less problematic if the user could opt to ADD data available below province. Then, if it matched label information, it could be selected to add to the record. Else, by default, it is not included. That approach would significantly reduce the potential for incorrect/artificial data being introduced to the record.

**Comment by cgendreau** [comment]
That can be changed for sure, thanks.
