### ISSUE TITLE
Material sample attachments

### ISSUE THREAD

**Issue by OwenLonsdale** [AAFC-BICoE/dina-planning#288]
When adding an attachment > Attach existing object

If I click on an original filename (by accident or in an attempt to see a thumbnail to verify the identity of the attachment), my opened specimen record is abandoned to view the object's view-only page. I therefore lose the data entered into my specimen record.
Can we protect the specimen record while dealing with attachments so this doesn't happen? If an attachment file is clicked on, perhaps a new tab can open to view the object record, or a window embedded in the add attachments pop-up is populated with an image of the object if it is a JPEG, TIF, etc?

**Comment by cgendreau** [comment]
Fixed
