### ISSUE TITLE
Determination must be exactly as in CoL, including subgenus

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#293]
Similar to issue #267. Another issue with the way Scientific Names are looked up in CoL.

I tried to search for one of our most common syrphids in North America, in the Scientific Name Search, that name is _Syrphus ribesii_. This is the correct, most up-to-date name. This name has been used for a very long time, and the species was described by Linnaeus, so it has a long history of use (meaning it should be found without issue).

However, I cannot find it using it's name. 

I looked it up on CoL and found the name listed as Syrphus (Syrphus) ribesii (Linnaeus, 1758).

I then wondered if I had to use the subgenus in my search....and I was correct. The only way to find this name is to enter Syrphus (Syrphus) ribesii. 

This is not going to work for looking up scientific names. There is no way that anyone but a very knowledgeable taxonomist will figure this out and have the knowledge to find the correct name. Subgenera are not always used and not often included on labels with scientific names.

This will also take more time to enter. For data entry, it will be faster to type fewer characters. A search of CoL should be much more robust and be able to handle partial names.

This will also mean that quite frequently, we may need to go to CoL to look up the exact way they have the name and use that to inform our search. Again, this will take up a lot of time, having to leave DINA to go to CoL, look up the taxon, then go back to DINA to enter it correctly.

**Comment by dshorthouse** [comment]
See comments on #267. It's a deficiency in search at CoL's end and we're working on a possible alternative service in collaboration with @dimus that has a more robust search.

**Comment by michellelocke** [comment]
That is great. I hope that we can find a solution that is more robust and works how we need it to.

**Comment by dimus** [comment]
Normal gnverifier search should find the right name with or without subgenus:

https://verifier.globalnames.org/?all_matches=&all_sources=&capitalize=on&format=html&names=Syrphus+ribesii

**Comment by dshorthouse** [comment]
Thanks @dimus. But the new gnverifier is _so_ much nicer :)~

https://verifier.globalnames.org/api/v0/search/n:S.+ribesii+L.

**Comment by dimus** [comment]
It probably does not matter for interactive use, but it is good to keep in mind, that 'normal' verification would  be 100-10000 times faster than 'faceted search'.
