### ISSUE TITLE
Convert to Elevation Min/Max does not convert in most use cases

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#300]
I expected the Convert to Elevation Min/Max, under Verbatim Elevation, to convert the Verbatim Elevation in feet to elevation in meters in the Elevation in Meters field. It is not robust enough to handle data entered in verbatim formats.

Ex:
Data Entered > Data "Converted" in Elevation in Meters field
- 1600 > 1600
- 1600' > 1600
- 1600 ft. > 1600
- 1600ft. > 1600
- 1600 feet > 487.68

Only one of five possibilities works and converts to meters correctly.

We almost always see verbatim elevation in feet indicated as 1600' or 1600 ft. (with or without a space, and since we are talking verbatim, it matters). Neither of these common formats are handled by the conversion button. In addition, if a user is forced to type "feet" for the conversion to work from verbatim, but they will have to make sure to change "feet" to represent how it is actually written verbatim on the label. A user should not have to enter data one way to get a result (feet), then change it to get what they actually want in that field (').

There aren't that many ways that feet are commonly represented on a label. The database should be able to handle all of the cases as indicated above.

**Comment by cgendreau** [comment]
Fixed
