### ISSUE TITLE
Error when removing "levels" from the Current Geographic Place

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#303]
Verbatim Locality: Kandy, C.P. / Ceylon
Search Verbatim locality > get result:
Ceylon Tobacco Company, Watapuluwa, Kandy District, Central Province, Sri Lanka [category: landuse]

Say I select this because it is my only option. I am then presented with four levels of geography, plus the State/Province and Country:
Ceylon Tobacco Company [ landuse ] 
Watapuluwa [ place ] 
Kandy District [ boundary ] 
Central Province [ boundary ] 
State/Province: Central Province
Country: Sri Lanka

I delete the landuse and place as I know they are incorrect.

When I try to save the record I get the error: 
Constraint violation: geographicPlaceNameSourceDetail.stateProvince.placeType must not be blank

In issue #273 @cgendreau states "You can remove all artificial information. There is an X next to all levels (except country and province)."

I cannot remove artificial data as I get an error why I try to do this.

**Comment by cgendreau** [comment]
Fixed
