### ISSUE TITLE
Open Material Sample Attachments in a new tab

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#305]
When in a Material Sample and you click on a Stored Object/Material Sample Attachment, it should open in a new tab.

It currently opens in the same tab, navigating the user away from the record they were on. This is not practical. Often a user wants both open and often, after they have looked at an image will want to return to the record. It is easier to do this with multiple tabs rather than navigating back in a single browser tab.

**Comment by OwenLonsdale** [comment]
This feature is so annoying I think I already mentioned it in ticket #288!

**Comment by michellelocke** [comment]
@OwenLonsdale similar but not the same. I am referring to a Material Sample Record that a user is viewing (the saved record). I think you are referring to a Material Sample that a user is editing. Two places where this needs to be fixed.

**Comment by cgendreau** [comment]
This is fixed in Edit Mode. In read mode you can do Ctrl-Click.
