### ISSUE TITLE
Object Metadata dropdown fields populate once opened, even if I click away and don't select a value

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#308]
After uploading a new Object and you are now on the Edit Metadata page. You click on a field that has a dropdown menu (ex: Orientation, Object subtype, etc.), you then view your options but decide not to select an option. You then click away from the dropdown menu to close it, without actually selecting a value from the menu. The field is then populated with the first value in the dropdown menu.

As the field populates if I open the dropdown menu, regardless of if I click on a value or not, I then must delete the value that I do not want. 

The field should only populate if you click on a value. If you click away from the dropdown menu you should still be left with the default of nothing.

**Comment by cgendreau** [comment]
The table after the upload is not there anymore.
