### ISSUE TITLE
Verbatim Determiner shows list of previous entries but doesn't filter

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#309]
When I am in a Material Sample and I want to fill in the Verbatim Determiner, I start typing a name. As I type, a list of my previous entries shows up below. As I keep typing, this list remains the same and does not filter based on what I am typing.

Two screenshots are below showing what I mean:

1 & 2: Name hasn't been entered before, as I type the list remains the same (see progress from 1 to 2)
3: Name already in the list, however it is still far down the list and list is not filtered as I type.

It would be really helpful if a history was kept so a user could draw from what they types previously but that list should filter as the user types so that they can easily select a previously entered option.

![Verbatim Determiner 1](https://user-images.githubusercontent.com/61324432/143503276-bb0ac4ab-9378-4ca6-83cb-abfd2a3182ca.JPG)
![Verbatim Determiner 2](https://user-images.githubusercontent.com/61324432/143503280-2c413efb-27c1-443c-a6bd-eca63fea7b8c.JPG)
![Verbatim Determiner 3](https://user-images.githubusercontent.com/61324432/143503368-1a589ca8-27b8-44ed-b0d7-66192bc4a758.JPG)

**Comment by cgendreau** [comment]
Fixed
