### ISSUE TITLE
requesting clarification regarding access to collection's data

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#314]
There have been some recent conversations which have indicated that collection's data in DINA will be 'open' or 'read-only' to "everyone". In one discussion, the person said 'all of AAFC' and in another discussion 'everyone on the network' was mentioned. That would include:
AGRICULTURE AND AGRI-FOOD CANADA
CANADA AGRICULTURAL REVIEW TRIBUNAL
CANADIAN DAIRY COMMISSION
CANADIAN FOOD INSPECTION AGENCY (CFIA)
CANADIAN GRAIN COMMISSION
FARM PRODUCTS COUNCIL OF CANADA
FARM CREDIT CANADA 

Most CMs assumed that their collection's data would NOT be viewable by default to unknown users. Please clarify who will have access to collection's data in the DINA media and data management modules, and how that will be controlled.

**Comment by cgendreau** [comment]
Current situation:

https://github.com/AAFC-BICoE/dina-planning/blob/master/docs/UserManual.md#permissions
"Read permission are given to all authenticated user" 

Authenticated User represents users that were given permission by a CM or an Admin based on your internal procedure(s).

If this is incorrect please create a new ticket explaining what is expected.

**Comment by heathercole** [comment]
@cgendreau  Thanks for this insight. Can you clarify what 'views' will be applicable between collections? If a collection manager approves a user, **do they just get access to the particular collection, or to all collections?**

Your 'current situation' reply makes, sense, there was some confusion, because there had been several comments made about the data being visible to everyone 'on the network'. 

Thanks!

**Comment by cgendreau** [comment]
At the moment they would get read-access to all collections.
