### ISSUE TITLE
Increase length of materialSampleRemarks & other remarks fields

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#316]
Toyed with import from DAOM today and received this error:

<img width="538" alt="Screen Shot 2021-12-07 at 2 27 50 PM" src="https://user-images.githubusercontent.com/326459/145093615-01a0b176-4fed-4a46-a119-9ec7002cbe07.png">

Remarks field lengths should be open-ended.

**Comment by cgendreau** [comment]
They won't be open-ended since there is always a limit. But it can be increased.

**Comment by dshorthouse** [comment]
> They won't be open-ended since there is always a limit. But it can be increased.

OK, let's make 500 for now. Satisfied my present content but I expect others may wish to write novellas.

**Comment by cgendreau** [comment]
Fixed. All remarks fields are increased to 1000.
