### ISSUE TITLE
Make project tags clickable

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#320]
GIVEN I have accessed DINA as a collection manager / user

WHEN I attach a material sample to a project

THEN I should be able to click the project tag

AND navigate to the project page

Conversely...

GIVEN I have accessed DINA as a collection manager / user

WHEN I have attached a material sample to a project

THEN I should see a list of linked material samples on the project page

AND each material sample there contains a hyperlink to the material sample view

**Comment by cgendreau** [comment]
It took a year but it's done :)
