### ISSUE TITLE
Restrictions

### ISSUE THREAD

**Issue by ron-reade** [AAFC-BICoE/dina-planning#329]
I noticed two issues with the restrictions section of DINA (hopefully these are not already reported... I tried a search):

1. Once you select a level, you cannot unselect it... so if someone accidentally selects PPC-1 you cannot go back to a black selection state in that box.
2. The restriction "button" selects even if you click way to the right of it (nowhere close to the actual button), so I accidentally marked something as restricted while looking at the PHAC menu.

**Comment by cgendreau** [comment]
Should be resolved now. Thanks for reporting.
