### ISSUE TITLE
Create a generic "Assemblage" module to contain a gathering of material samples

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#334]
GIVEN I have accessed DINA as a collection manager

WHEN I wish to organize material samples according to some organizational theme that is different from say projects or taxonomy

THEN I should have a mechanism to assign one or more material sample(s) to this user-generated assemblage

AND each assemblage should have the following fields:

`title` (English and French), `description`, and capacity to have managed attributes as do other modules.

The immediate use-case here is for DAOM's exsiccatae that have a title, a description, and a loosely described storage, which would be best expressed as a managed attribute. While each material sample could of course have permanent storage, the organizational bundling of these exsiccatae and its relationship to the overall, physical location of the bundle is meant to act more like a gestalt finding aid than it is to have any direct bearing on transactions as would storage.

Additionally, when I view an `Assemblage`, then I should see a list of all associated material sample(s) with the ability to individually add/remove items.

**Comment by cgendreau** [comment]
Definition added to the user guide: https://aafc-bicoe.github.io/dina-documentation/#assemblage

**Comment by cgendreau** [comment]
Done
