### ISSUE TITLE
search shouldn't clear out window when switching search field

### ISSUE THREAD

**Issue by rintoult** [AAFC-BICoE/dina-planning#340]
i was just playing with the search feature on the object store. 

i searched a word in caption and then switched to wanting to search for it in orignal file name. 

it cleared out my search in the second window. 

i often might want to search the same term in two different locations - or might choose the wrong thing from the pull down menu. 

don't want to have to keep retyping the search term. 

tara

**Comment by cgendreau** [comment]
What is the "second window"? Another browser tab or the text box where you enter text ?

**Comment by rintoult** [comment]
where the search term goes, the text box

**Comment by rintoult** [comment]
another searching issue - is navigating out of details and back to list is also clearing my search. 
eg I search for daomc 252410 primary ID
It gives me 12 results. 
I look at the details for DAOMC 252410 B want to go back to look at one of the other material samples. 
I hit back to list view. 
It shows me the whole list again - not the list of what I searched for. 

Tara

**Comment by rintoult** [comment]
added the other data users for their input

**Comment by cgendreau** [comment]
I moved the issue in comment to its own ticket: #345

the main one is resolved.
