### ISSUE TITLE
Create FLOAT vocabularyElementType

### ISSUE THREAD

**Issue by juliadouglasf** [AAFC-BICoE/dina-planning#353]
The current vocabularyElementTypes are INTEGER, STRING, PICKLIST, DATE, and BOOL. None of these data types are ideal for numbers with decimals. I propose adding a FLOAT data type or something of a similar nature to properly capture numbers with decimals.

**Comment by cgendreau** [comment]
API now has the type DECIMAL but the UI doesn't have it yet so I will leave the ticket open.

**Comment by cgendreau** [comment]
Done
