### ISSUE TITLE
Sort by multiple columns in summary table

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#41]
From @rintoult

Can we sort by multiple columns in the summary tables, ie Date created and Filename?

**Comment by cgendreau** [comment]
We will fix the tooltip but it is already possible if you hold `Shift` and click the second column.

**Comment by hacole01** [comment]
In the stored objects (table view) 
multi-column sort seems to work, but could not select 'upload by' for sorting
(is there a limit to the number of columns that can be added to the sort? - may be useful to include that info in the tool tip (was good tip)

bonus:
side note; column display/hide option that is available on the 'edit' page might be nice here. conversely, the sorting available here may be very useful on the edit page view.

**Comment by cgendreau** [comment]
Sorting by agent will be done in Release 2 so I moved this part to #84 .
