### ISSUE TITLE
Upload multiple files with separate drag and drop actions

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#42]
From @rintoult:

You can only upload files from one location at a time – with the drag and drop I was trying to build up a list of files I wanted to upload from multiple locations   and I could only do it by one source file at a time. Actually change that –   even if they are in the same location you can’t sequentially drag and drop files, it has to be all in one go or separate upload actions. The first one gets replaced by the second one if you try to do them separately.

**Comment by hacole01** [comment]
this seemed to work as intended. I tried added files from different network folders at the same time as files from my desktop, as well as files grouped together with files selected using control (not in order). I did not actually upload them all, but selection seemed to work, as edit-table opened.

**Comment by hacole01** [comment]
i did get an error on one of my attempts, will try to re-create to better document

**Comment by hacole01** [comment]
regarding the error reported above, I believe it was caused by the upload of .cr2 (canonraw) file types. I tried uploading a single .CR2, and received the same error.

**Comment by cgendreau** [comment]
What the size of that cr2 ?

**Comment by hacole01** [comment]
> What the size of that cr2 ?

not sure size of that exact one, but reviewed a folder of ~14,500 DAO images in .cr2 format, sizes range from 23,351 KB to 32,750 KB.

DAO types (~1000)  (.tif) range from 14,441 KB to 204,573 KB (scans on super high-resolution inverted scanners - Global Plants Initiative project)

**Comment by cgendreau** [comment]
ok, that should work but I just noticed you also said pdf, .jpg, .cr2

**Comment by hacole01** [comment]
> ok, that should work but I just noticed you also said pdf, .jpg, .cr2

I was trying all those filetypes at the same time when I first documented the upload error. I repeated the error using only the single .cr2 (have not tested .cr2 of varying sizes)

strangely, got this error when I tried a .pdf **INTERNAL_SERVER_ERROR: expected acMetadataCreator being an attribute expected:<ATTRIBUTE> but was:<RELATIONSHIP>**
but i think it was because I selected 'x' to remove the .cr2 that failed, then put the .pdf in and tried to save. When I refreshed the upload page, the .pdf loaded without isssue.

**Comment by cgendreau** [comment]
I tested cr2 and it's working as expected (no preview but that's normal for now).

I think we can say that this issue:

>  Upload multiple files with separate drag and drop actions

 is Resolved.

**Comment by hacole01** [comment]
hmm, I just tried an upload of several objects and file types and it failed (see images for files I tried to upload and result).
1. tried upload all (drag/drop then hit save), nothing happened (but red banner at top)
2. tried removing .mp4 and save (still nothing + red banner)
3. tried removing really long-named .pdf and save (no success)
4. tried removing files with brackets in the name (no success)
5. tried to hit refresh (remaining files all disappeared/wiped/upload reset)
![test upload](https://user-images.githubusercontent.com/50373105/102814491-ba9eee80-4398-11eb-8284-7749dd615f6d.png)
![test upload error](https://user-images.githubusercontent.com/50373105/102814510-c094cf80-4398-11eb-9776-058ece3c43eb.png)

**Comment by cgendreau** [comment]
ok, we will have a look.
I don't believe the file type is the issue, probably more the overall size that is more than 1 GB (it is expected to work but since it's a test server).

**Comment by hacole01** [comment]
I just opened a related ticket https://github.com/AAFC-BICoE/dina-planning/issues/76 regarding "behaviours" in the case of upload issues. perhaps a file-size warning is also relevant.

**Comment by cgendreau** [comment]
There is now better mechanism to display and limit file size based on the configuration of the system. If there is issue plus open another ticket since "Upload multiple files with separate drag and drop actions" is functional.
