### ISSUE TITLE
Search by uploaded date is not working

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#43]
On the demo site the search by date is not working. A file uploaded today (2020-09-30) can not be found with a query date > 2020-09-29.

The search is applied to the Date Original Version which is a field that's is currently always empty.

cc @rintoult

**Comment by rintoult** [comment]
Shouldn't wa also have an option for "is equal to"  or is the plan that you would have to create a range on either end of the day you are interested in?

Also if you built up a range that includes less than AND greater than - does it exclude or include the days in the query?

Tara

**Comment by cgendreau** [comment]
We may need to review how it is presented since it might be confusing but `greater than` is almost a `greater than and equals` but not exactly. In reality, the field is a date-time. So there is a time component but it's not displayed. It means that unless you uploaded something on a date at midnight, 0 minute, 0 seconds, it will be returned with a `greater than` for the same date.

The easiest thing to do is probably to simply change that to a `greater than and equals` since it's probably the most common use case. The `equal` could also be added and it would be transformed to a range query.

**Comment by rintoult** [comment]
Tested this today with less than 09/27/2020 and I was still seeing everything that hadn't been uploaded until November?

Also the lingo maybe should be changed? 
less_than -Before
Greater Than -After

And still no option for searching a single date.

**Comment by cgendreau** [comment]
Single date will be included in #44 .
As for the less than, are you using the Date Original Version created or the Metadata Applied Date (I know not super good names, we will improve them) ?

Date Original Version: only working on new uploads and it represent the last modified date of the file on your computer before you upload
Metadata Applied: when the record was last updated

**Comment by rintoult** [comment]
You are right - I was searching on the wrong date/looking at the wrong column. 

It works!
