### ISSUE TITLE
Improve search by date

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#44]
Improve search by date to make it `greater than and equals` and also support `equals` operator.

cc @rintoult

**Comment by shannonasencio** [comment]
Calendar to select date does not display properly.

**Comment by cgendreau** [comment]
Could you give more details since it's working as expected from what I can see.

**Comment by shannonasencio** [comment]
The calendar was cut off at 100% zoom. I zoomed out and back in and it does display properly now. However, that probably shouldn't be happening at all (?).

**Comment by cgendreau** [comment]
I tried different combinations and I could not reproduce the issue. Indeed it should not happen so if you see it again please open another ticket. Thanks.
