### ISSUE TITLE
Limit to file size to add to object store?

### ISSUE THREAD

**Issue by rintoult** [AAFC-BICoE/dina-planning#45]
I was playing around with the object store again - before doing the targeted issue review. 

I has some issues with uploaded two high quality images. Is there a limit to file size - or was it a network issue. 

This is the error message I got:
/objectstore-api/file/ccfc: undefined 

There also seemed to be some very long upload times for the drag and drop action. This might be related to my wifi or network connection of cours. 

Tara

**Comment by cgendreau** [comment]
Yes there is a file limit and it should be displayed on the page so we will have a look.
We will contact you to test the high quality image. Thanks.

**Comment by cgendreau** [comment]
The current limit on the test server is 50MB

**Comment by rintoult** [comment]
They were not that big! 

Just tried again - pretty sure it was a network/connectivity issue. Think this can be closed. 

Tara

**Comment by cgendreau** [comment]
Sounds good. We will still look if we could improve the error message.
