### ISSUE TITLE
Rights Statement should be editable

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#47]
Rights Statement should be an field editable by the user in the upload and edit view.
Reported by @shannonasencio

**Comment by hacole01** [comment]
- typo in License drop down (licenSe not licenCe)
- Is 'rights statement' the correct terminology for this field? 
- is "Copyright Government of Canada" the correct text? were the appropriate groups consulted?
     - vs. Crown Copyright Canada

-----
From: Cole, Heather (AAFC/AAC) 
Sent: Monday, December 30, 2019 11:50 AM
To: Bilkhu, Satpal (AAFC/AAC) <satpal.bilkhu@canada.ca>; Malouin, Christian (AAFC/AAC) <christian.malouin@canada.ca>
Cc: Shorthouse, David (AAFC/AAC) <david.shorthouse@canada.ca>; Macklin, James (AAFC/AAC) <james.macklin@canada.ca>; Lybaert, Anissa (AAFC/AAC) (anissa.lybaert@canada.ca) <anissa.lybaert@canada.ca>
Subject: Copyrights and Licensing for portal

Hi folks,

I’ve been talking to a member of AAFC’s ‘Office of Intellectual Property and Commercialization’ regarding copyright/licensing/attribution embedded in our image file properties, this will hopefully help structure some aspects of the multi media server. The conversation also raised the issue about all of those things for general use of the files and data that would be available on the portal.

She indicated that it would be important for the Portal to include a ‘conditions of use’ type of page, as well as some sort of pop-up/box-tick that requires people who download anything to acknowledge said conditions of use of data and digital assets. Similarly, documentation to that effect should currently be used whenever collection managers share digital assets (eg. images/data).

I imagine that this topic may be quite far down on the ‘to-do list’ for your group, but I wanted to pass this requirement along to ensure that it is on the list somewhere.

Regards,
Heather

**Comment by cgendreau** [comment]
It is licence with a 'c' : https://open.canada.ca/en/open-government-licence-canada

**Comment by hacole01** [comment]
> It is licence with a 'c' : https://open.canada.ca/en/open-government-licence-canada

oh dang, field header is 'licenSe' should we pick one? seems like for (British English) 'licence' is correct?

**Comment by cgendreau** [comment]
Yes it should be consistent and I would use the one that open government is using.

**Comment by heathercole** [comment]
Hi, 
Maybe I am confused, but this doesn't appear to be "done" on upload I don't see any option to change the rights statement in the upload or edit functionality. 

I think the current default is a good default, but should be able to change to either empty or text to indicate the Rights do not belong to AAFC/GOC for material that AAFC is not the owner of.
