### ISSUE TITLE
object store metadata issues

### ISSUE THREAD

**Issue by hacole01** [AAFC-BICoE/dina-planning#48]
Hi,

I have a few concerns with the details displayed with uploaded images. Many of them have been discussed in our requirements-gathering.
1. There is no owner listed. This is a vital component of open government/open data and relevant licenses., particularly with digital images. 
2. "Date Original Version Created" this seems to indicate the upload date of the digital file. But this header IMPLIES that it is the date the image was taken. The image taken date would be integral to display with the image data. It is typically held in the file meta-data.
3. may be relevant to have ‘publicly releasable’ default = yes for images, and no for other types (eg. docs). Can this be bulk-edited?

**Comment by cgendreau** [comment]
1. Could you elaborate on what you mean by owner? You can currently set the License and the Copyright Statement. There is also a field that is called [RightsOwner ](https://terms.tdwg.org/wiki/Audubon_Core_Term_List#xmpRights:Owner) but it is not available in the user interface at the moment.
1. The date doesn't not represent the date of upload but the date of the digital file that is uploaded. The default value is the last modified date from your file system when you upload the image but it can be changed by the user if not accurate. EXIF data can be extracted but it will only be available in release 2.
1. Yes we can change the default value and add it to bulk-edit.

**Comment by hacole01** [comment]
1. Yes, Rights Owner. In addition to License and Copyright, this is vital data to have available for effective sharing for Open Gov/OpenData, particularly when licenses request attribution.
2.  In Windows systems, date modified is often updated if a file is moved. I am not sure who that would be relevant to. If the date NOT the date of the original version (eg. when the photo was taken), field name should be changed to reflect this. In most cases, even calling it 'modified date' would be misinformation for specimen images which may have been moved several times. If this is a relevant field, description should be changed and additional field must be available to display DATE TAKEN, which (since already embedded in most image files) is not reasonable to request that anyone input manually. For collection management, the date the image was taken is 
3. Default values would likely be very effective, in addition to bulk-editing options for some (not all) users.

**Comment by hacole01** [comment]
"Date taken" is also an important component for manager's reporting numbers

**Comment by cgendreau** [comment]
1. The rights owner is almost always the one in the Copyright statement so making it 2 fields with overlapping data also opens the door to mismatch.
2. "Date Original Version Created" is the date taken (for images). The current value is only the best possible estimation at the moment and should always be validated by the user uploading the image. It will be no different with a date/time extracted from the camera since you can't be sure that the date/time is accurate on the camera (even if it's far more reliable)
3. This is now in it's own ticket #56

**Comment by hacole01** [comment]
regarding #2 
I just uploaded an image  http://dina-ui-template-dinaui.apps.biodiversity.agr.gc.ca/object-store/object/view?id=534f91ea-d48c-4922-bc42-3b49c0fbf1b7

the "Date original version created" matches the modified/created date (which is changed whenever the file is moved in Windows based systems) which is not the same as the "date taken" date. As there are often many 'moves' associated with file management, it is the "date taken" date which is useful to managers (Rarely the modified/created dates).

![dina image file properties](https://user-images.githubusercontent.com/50373105/98974301-c0c0c600-24e2-11eb-9fdf-70ca640ed409.png)

**Comment by cgendreau** [comment]
Yes, because we are not extracting the exif at the moment as explained in https://github.com/AAFC-BICoE/dina-planning/issues/48#issuecomment-724689740

**Comment by cgendreau** [comment]
Please create a new ticket for Date Original Version Created so we can track it. I would like to close this tickets since there is too many subjects. The ticket should suggest to extract exif (we will try) and mention what is the expected is it`s not possible (if nothing is better than the last modified date).

**Comment by cgendreau** [comment]
Closing since all issues are now in their own tickets.
