### ISSUE TITLE
upload to more than 1 group

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#49]
some users will need permissions to upload to more than one collection
eg. Shannon manages 2 collections
eg. May be relevant for CCFC/DAOM to have cross-access

**Comment by cgendreau** [comment]
Sure, that's not a problem but you can't upload to 2 groups at the same time.

**Comment by cgendreau** [comment]
Ready to be validated. You are now part of 2 groups (for testing)

**Comment by heathercole** [comment]
i was able to upload objects to the aafc and dao groups
