### ISSUE TITLE
view/filter by agent who uploaded (or NOT) has unclear terminology

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#50]
This requested functionality seems to be in place but obscured by strange field title "ac metadata creator" . Not clear if metadata creator and uploader/"uploaded by" are always the same agent (probably?)

Functionality seems good to select uploader AND/OR restrict (eg. collection manager may want to review all uploads NOT by them)

**Comment by cgendreau** [comment]
Yes titles are not very clear. They will be changed.

**Comment by hacole01** [comment]
i do not currently see how to filter objects by the agent who did (or did not) upload them.

**Comment by cgendreau** [comment]
Metadata Created By, there is also a tooltip on the header of the table with the current definition.

**Comment by hacole01** [comment]
the terminology seems to be getting more confusing. If someone wants to search by who uploaded the object, then it would be effective to call that field "uploaded by". Related, most uploaders may not be responsible for the metadata, and will be following instructions. Perhaps I am not clear on what use-case requires a filter by metadata source-agent.

**Comment by cgendreau** [comment]
Currently uploaders in the user interface are responsible for the metadata, there is no other field to track that. So if you upload an object using the interface you are the metadata creator in the sense that you created that record. There is an Upload By field internally that can contain other values for example if a script is used to move data but this field is not searchable. So you could create records from the conveyor belt system and they will be moved by a script. In such case the Uploaded By would be the script and the Metadata Creator you.

**Comment by hacole01** [comment]
I don't understand all the terms being used in this module and in the replies to issues. The module would need less explaining and be more straight-forward to use if the terms and fields were more consistent with terms used by biological collections and lay-people.

**Comment by cgendreau** [comment]
Terms are well defined in the community and are used accordingly by the module.
https://tdwg.github.io/ac/termlist/#ac_metadataCreator
https://tdwg.github.io/ac/termlist/#dc_creator

The labels can be changed but we would need concrete suggestion.

**Comment by hacole01** [comment]
I suggest that to identify the person who uploaded the object, the label be "uploaded by". I think that label would not need to be explained and be most efficient for most users of the module.

**Comment by cgendreau** [comment]
If a record is uploaded by a script, what the value of Uploaded By should be ? The Agent who started/configured the script or the script itself ?

**Comment by hacole01** [comment]
I don't know the different ways/objects that upload scripts would be used, but I can see that there would be value knowing that it was. I think ideally you would know the name of the person responsible for running it, but also possibly (other field?) that it was manually vs. automatically (script?) added? 

In the case of a completely automated upload (maybe if one is developed from conveyor belt upload), then I would think that it would be relevant to have names associated with those scripts/uploads which identifies them as the source of an upload. For example, if at the end of a day on the conveyor belt, a student starts a program that runs some sort of upload script, I think the script would be the uploader, not the student. The same student, in other workflows, may actually manually add objects, in that case, i would think they would be the 'uploader'. 

From your mention of 'configuration' above, it sounds like there good be a use-case that is somewhere in the middle, where a person configures a script for upload, if that script can be configured in different ways at different times and used by different people, I can see value in being able to separate those from objects the same person uploaded without a script. 

From my discussions with Collection Managers, it is a case of them wanting to be able to see/review materials uploaded by certain people, it seems reasonable that they may categorize manual vs. uploaded scripts differently, and may want to be able to tell them apart. 

Happy to discuss further, or consult collection managers if there are specific questions that need to be answered.

**Comment by cgendreau** [comment]
Ready to be validated. The field is now renamed to `Uploaded By`.

**Comment by heathercole** [comment]
will have sign-off on this and related fields shortly :)
