### ISSUE TITLE
picklist/controlled vocabulary for managed attributes

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#54]
the requirement for controlled vocabulary/pick lists was communicated in several meetings

WHEN a new managed attribute is created

THEN there should be an option to create a controlled vocabulary/pick list of acceptable entries for the attribute

AND this should be editable (eg. add/remove entries) as required.

**Comment by hacole01** [comment]
i see this implemented in the SpecimenView Managed attribute, but when i try to create a new managed attribute, i am only offered 'string' or 'integer' options.

**Comment by cgendreau** [comment]
yes, select String then you can add values with Accepted Value.

**Comment by cgendreau** [comment]
This feature is implemented and functional as described.

**Comment by hacole01** [comment]
The functionality is not clear. At the very least the headers could be edited; 'sting' could be changed to 'text/pick-list' and 'integer' could be changed to 'numerical'. This would make this significantly more approachable to users (who are not developers)

**Comment by cgendreau** [comment]
We can indeed change labels.

**Comment by hacole01** [comment]
i suggest the labels be changed to "text or picklist" and "numerical"

**Comment by cgendreau** [comment]
Yes that can be changed that, as long as it is understood that Numerical can't have a decimal part (at least for now).

**Comment by hacole01** [comment]
perhaps "numbers" or "values" but not sure those are any more helpful, but "seem" to possible imply less precision than 'numerical'. Let me know if others should be consulted.

**Comment by cgendreau** [comment]
This is done and ready to be validated but keep in mind that there is still the issue related to #70
