### ISSUE TITLE
display issue with Managed Attributes dropdown on file upload

### ISSUE THREAD

**Issue by hacole01** [AAFC-BICoE/dina-planning#55]
after adding images and hitting 'save', when the "edit metadata" page is displayed for uploader to enter data. If you select the 'Managed Attributes' drop down, part of the list is obscured/hidden by the table displaying the file uploads.

![dina dropdown blocked](https://user-images.githubusercontent.com/50373105/98708908-b3270700-234f-11eb-8cad-3eada76c5b58.png)

**Comment by cgendreau** [comment]
Ready to be tested. Please Close the issue after validation if the issue if resolved.

**Comment by hacole01** [comment]
checked onsite and via vpn, display issue seems resolved
