### ISSUE TITLE
‘publicly releasable’ field default 

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#56]
The definition of this field is not entirely clear, but if meant to be used by collection managers to indicate whether an object is appropriate to release to public, then it would probably be made much more effective by having default values assigned for particular file-types. (eg. images, default likely = yes/true), but perhaps left blank or No/False for document file formats which may require review/clearance.

Would also be relevant for appropriate managers to be able to bulk-edit this field.

**Comment by cgendreau** [comment]
What appropriate managers means? Staff should not be allowed to change the value of publicly releasable ?

**Comment by hacole01** [comment]
> What appropriate managers means? Staff should not be allowed to change the value of publicly releasable ?

Sorry, not clear on what you are asking (or if directed to me or not) ;)

**Comment by cgendreau** [comment]
You said:
> Would also be relevant for appropriate managers to be able to bulk-edit this field.

Please explain **appropriate managers**

**Comment by hacole01** [comment]
appropriate managers = folks with higher permissions for a particular group, eg. collection managers, data managers.
I think this depends on how this ends up being implemented (currently not editable). If some related fields are (or are not) populated on upload (eg. are all images default=true, and all documents=false (is this set on upload?). My thoughts are that it is likely would not want all users (eg. students to be able to change "releasable = false" to "true".  Collection managers should be consulted for their use-cases.

**Comment by cgendreau** [comment]
We can change the default value of `publicly releasable`, that's not a problem. Permissions are not granular enough to allow this level of control so we will need to review that later.

As for the reason of `publicly releasable` there is some interesting controlled vocabulary that could be used. See https://www.si.edu/sites/default/files/unit/OCIO/si_dams_metadata_guidelines_mm16_2020.pdf section `SD 609 Restrictions`
