### ISSUE TITLE
adding agents and agent-relevant data

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#57]
I have a few concerns with the 'adding agents' feature, it isn't clear how this field may (or may not) be relevant to the collection management module.
1. is this for active users or also for names in the datasets? 'agents' is commonly used to represent all names (both user and other) in collection databases. is it also for collection clients?
     - if this is just users, then it may be relevant to only accept @canada (or other institutional emails) as it is likely not appropriate for the system to be maintain personal information. (but maybe relevant if clients are also agents, if that is the case, then accessibility/view-ability of the field may be relevant to restrict (and certainly not publish)
- if 'agents' are also names from the database, then there are MANY that will have no email address
- if 'agents' include colleagues and contacts which relate to loan transactions, then there are additional data fields that would be relevant, as well as being able to populate them when the agent is being created/added
- telephone number
- name of collection
- name of institution
- number of active loans to/from

2. will there be capacity to identify aliases/alternative name formats to associate agent names? Eg. Paul Catling is Paul M. Catling, but not P. Catling (because there is also Paula Catling?)

**Comment by cgendreau** [comment]
The focus is currently limited to object-store. Therefore, an email will always be available.

**Comment by hacole01** [comment]
My team has the use case of a casual employee, who isn't using an AAFC email address, it would not be necessary or appropriate for their personal email to be included. They will have an AAFC LAN id, which would be recorded in the 'photo taken by' exif of a digital image they create. It is not clear to me how that fits within actions on digital object ('is this 'digitized by'), in which case, it would be an agent, without an email being relevant.

**Comment by cgendreau** [comment]
done
