### ISSUE TITLE
duplicate file uploads possible; need flag/warning

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#59]
As a test, I added 2 copies of the exact same 4 files (same location) (dragged separately) into the upload. The system let me upload these without issue. 

For quality control and effective asset management, there should be a warning if there is more than one file with the same name being uploaded AND there should be a warning if a file is being uploaded to a group where a file with the same name already exists.

**Comment by cgendreau** [comment]
Thus target implementation will actually check at the digital file signature. In other words, we can detect duplicate even if they have a different name. The check will be don against all objects regardless of the group.

**Comment by hacole01** [comment]
> The target implementation will actually check at the digital file signature. In other words, we can detect duplicate even if they have a different name. The check will be done against all objects regardless of the group.

please note that there are cases where files have identical hash data BUT different file names to represent different collection objects (multiple objects in same image). This doesn't mean that a single image couldn't be linked to more than one collection record, but current implementation created a file for each, with the object identifier as file name. Just a use-case to track.

**Comment by cgendreau** [comment]
It will just be a warning, the user can still proceed and save.

**Comment by hacole01** [comment]
> It will just be a warning, the user can still proceed and save.

would be optimal if there was also the option to review/replace existing version. As discussed, in many cases, collection managers will not want to maintain old versions of images (eg. a specimen has a new annotation, would not want to maintain image missing newest annotation, would only want to maintain current version).

**Comment by cgendreau** [comment]
That would be a different use case. A new annotation on the specimen would generate a new image with a different hash. For the object-store it is a "new" object. The difference will be at the collection component level where you will change the link to the image to the new image and flag the old one for deletion (this will be done automatically, it is just to illustrate how it is working).

**Comment by heathercole** [comment]
the duplicate check should exist across all groups/collections. many people will need to view objects from multiple collections so it is vital that there not be different objects with the same name. I understand that from a hash perspective they may be different, but for most users, it will be the filename (or whatever is the primary VISIBLE) identifier that will be the most informative to them and what they "call" it.

**Comment by jmacklin** [comment]
I am not sure that the filename is very relevant here. In DINA, the filename is just a label with the hash and the database identifier being the critical information that allows each image/object to be unique. The filename itself has no requirement to be unique for this reason. I would think it is also not the case that the filename would be used to find images/objects as the search over relevant metadata attributes will be more effective. I agree that if the file is removed from DINA then having a human readable filename could be valuable but it is the image/object in DINA that remains the primary object, the other is a copy/duplicate. If CMs do want filenames to be unique then this can become a best practice in forming them going forward.

**Comment by heathercole** [comment]
@jmacklin  at the moment, the primary information being displayed for user referral is the "original filename". People need to be able to "call" these objects something and for it to be clear what they are talking about. That may not need to be the actual "filename" but the "filename" is what the system is currently displaying as the identifier for the media object. I am saying if that whatever identifier is presented to users, should not be duplicated. Related, users need to be able to search on an identifier, and have it only return one object, even across collections. That identifier should be visible. 

Perhaps if the end-product functionality is described/explained it would clarify if collection requirements are met, as the current implementation is displaying filename and this relates to an issue @michellelocke is working on to identify what data gets presented in a "display name" or #69 caption capacity. It would perhaps save a lot of effort/discussion on both sides if there was documentation provided about the intended display/identifier/filename in terms of functionality and displayed info.

**Comment by cgendreau** [comment]
All objects in Dina are uniquely identified with UUID. You can see it in the url on all detail pages. It can be displayed on the page, that's not a problem.

**Comment by cgendreau** [comment]
message updated
