### ISSUE TITLE
please use "date taken" date for images in  "Date Original Version Created" field

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#62]
The field name "Date original version created" implies that this field indicates the date the file was created. Instead it seems to hold the file's "Last Modified Date". 

For images, the "date taken" is a required field, for asset management, record keeping, and reporting. This date fits the field header/title more appropriately.

Current methods of image file management often require moving the file around a lot (eg. move off computer where image was taken to storage on a server), which updates the "date modified" field, but not "date taken". Additionally, if a derivative file is created (eg. a lower quality version of an image), then that file would have a 'created' date more current than the actual 'date taken'. 

not clear on Collection use cases for tracking the file creation date, and as the 'modified date' is often artificial (created when a file is moved), I am not sure who would use this for images.

Similarly for other file types, if this field actually presents "date last modified" the field header/title should reflect that. If there is a use-case for presenting/tracking this date, then a separate field for "date taken" for image files should be created.

**Comment by cgendreau** [comment]
This is now available for testing. It is also possible to view all the EXIF data in the Preview panel (or on the metadata details page).

**Comment by hacole01** [comment]
Hi,
I am not quite sure what to test. The "between" option for the date search/filter is really great, as this is exactly what managers would need for reporting, however, the result are not clear, as I am looking at some .jpgs that do not seem to have their 'date taken' info showing anywhere, and instead seems to be displaying the file creation date, which is artificially created when files are moved between drives. I am not sure that these windowsOS-generated dates are reliable/relevant for this purpose. Using this uploaded object as an example http://dina-ui-template-dinaui.apps.biodiversity.agr.gc.ca/object-store/object/view?id=921b4819-5e05-4918-b034-2091bd368a51. I have attached an image of the file properties which show a modified date earlier than the created date (could be possible), which do not match the data shown in the file record

There are 2 date fields displayed prominently in the record (created and modified) which are completely artificial, while the relevant date (for specimen images) is "hidden" much further down the page and with a vague (for specimen images) title name.

Related to this field, I think it may be worth considering whether 2 fields should be used. As for documents, recent version and modified -dates maybe be relevant, while as for images, the 'date taken' is what is vital. The current displays of these dates creates a significant opportunities to present misleading/artificial information.

It isn't clear to me what functionality is meant to stay within this module, vs the management tool module.

What is vital, is that collection managers can search on the "date taken" data for specimen images, and that this is presented as "date taken". I will consult with the collection managers as to whether there is any need for displaying the created/modified dates for specimen images, as the current display creates confusion around this data.

**Comment by cgendreau** [comment]
What should be tested: Please use "date taken" date for images in "Date Original Version Created" field .

So, if you upload a new image, is the date taken used (Date Original Version Created) ? Based on your example it is the case.

The object-store says:
Date Original Version Created 2015-10-27, 1:04:51 p.m.

**Comment by hacole01** [comment]
yes, the 'date original version created' DOES reflect the correct 'date taken'. So that is great, but this very important "date taken" date is obscured/difficult to assess as the other date fields/titles (eg. date created) are shown right at the top. I don't think other document types would have any information in this field, so would help by renaming the field. 

I have it at the top of my list to consult the collection managers as to whether the other dates (eg. created/modified) from the general file info are relevant to see for images (or any other files). I think most of us are very used to Windows "playing" with these dates, and do not find them informative, but will review. For these, the uploaded date may be more relevant.

**Comment by cgendreau** [comment]
Sure but this ticket should be restricted to the first part (the 'date original version created' DOES reflect the correct 'date taken') and be Closed since the work is done. A new one should be opened to track how and where to display it.
