### ISSUE TITLE
Capitalize Group Names

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#67]
I would like to see the group names capitalized (ex: CNC not cnc). I would think the others would agree but it would be good to consult other Collection Managers. We are used to staring at these capitalized acronyms all day long and it is not as easily recognizable to my brain in lower case. It's a small thing but I feel it makes a difference. 

@hacole01

**Comment by cgendreau** [comment]
Sounds good, we can rename groups that are acronyms.

**Comment by rintoult** [comment]
I agree that the group name ccfc should be edited to CCFC. I am also submitting another bug with a lot of questions of what groups are and how they are managed.

**Comment by cgendreau** [comment]
It will be changed in Release 2, moving the ticket.
