### ISSUE TITLE
Edit Metadata page not displaying properly

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#68]
On the Edit Metadata page when I add a Managed Attribute, such as SpecimenView, the cell with the name SpecimenView does not entirely show up. (See attached photo). Once I click into the data entry cell below it then shows up. I am using Chrome.

![IMG_1781](https://user-images.githubusercontent.com/61324432/102505726-56a2c000-4050-11eb-9976-3743bb65ac40.jpg)

**Comment by cgendreau** [comment]
This is fixed and ready to be validated.

**Comment by michellelocke** [comment]
This appears to be fixed. When I add a Managed Attribute the cell name appears entire now. I have not seen the glitch reappear. Thanks!
