### ISSUE TITLE
Capture documentCreator as text

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#7]
Specification level issue.
See https://github.com/DINA-Web/object-store-specs/issues/64

**Comment by shannonasencio** [comment]
Can add text without linking to agent, but does not save.

**Comment by cgendreau** [comment]
Actually the latest status is that an agent is actually required and the the app allows one to be created on-the-fly.

**Comment by shannonasencio** [comment]
Yeah, that works fine (already tested for issue #15).

**Comment by hacole01** [comment]
is this the same as uploaded by? does it refer to digital copy or document content? Need to be careful regarding appropriate/not appropriate attributions. Or maybe document creator is author? (vs. uploader?) in both cases, likely neither are owner?

**Comment by cgendreau** [comment]
It refers to the creator of the digital representation of an object. So the person who took the image (photographer).

**Comment by cgendreau** [comment]
`documentCreator` is an agent. The label of the field is changed by another ticket.
