### ISSUE TITLE
After Editing the Metadata of a single record it always returns you to the Object Store.

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#71]
When I edit a single image record (Edit Metadata) and hit save I am taken back to the Stored Objects page rather than the image record. If I cancel my editing I am also taken to the Stored Objects page. I can see that this makes sense when multiple records are selected but if only one record is selected it does not. I would think most people would want to be taken to the image record page so that they can see the changes they made after editing a single record.

If editing a single record I would like to be returned to that record after the Edit Metadata page, rather than be returned to the Stored objects page.

**Comment by cgendreau** [comment]
This is fixed and ready to be validated.

**Comment by michellelocke** [comment]
Yes this works as anticipated. After editing a single record (or canceling the edit of a single record) you are returned to the record and after editing multiple records (or canceling the edit of multiple records) you are returned to the object store. Thank you!
