### ISSUE TITLE
Editing the metadata of a single record

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#72]
Editing the metadata in a row format is not practical all of the time. If I am working on a single record on a small screen (like my AAFC provided laptop that I use at home) I cannot see all of the categories and have to scroll from left to right, with a lot of blank space underneath. This is frustrating. It would be easier to see a single record if these items were in a list format (maybe two rows, one for the name and one for the value or have it look more like a the data entry pages we currently use on CNCDB). 

When managing several photos at once a table view will be the easiest way to add data, but when editing a single photo it is not.

FileMaker has "form", "list, and "table" views which you can toggle between. Something like this would be much more practical. It would be great if we could toggle between views when editing but if this is not possible then minimally I would like the option to edit a single record in "form" or "table" view and when editing multiple records only use "table" view.

**Comment by cgendreau** [comment]
Ready to be validated

**Comment by michellelocke** [comment]
This is great! Thank you.

Is there a way to set it up so that we can toggle between seeing the data in this "form" format and seeing the data in "table" format (as is the style for editing multiple records)?

**Comment by michellelocke** [comment]
In this form format, it would be great to be able to select which attributes we want to edit and the order we want then to appear (currently can only select Managed Attributes). We should be able to customize the order for any and all attributes in any order we chose. It would also be good to be able to save and use the templates implemented in the group editing function.

**Comment by cgendreau** [comment]
Customization will be addressed in a later, global, step so it can work on all views.
