### ISSUE TITLE
Can't view stored objects today

### ISSUE THREAD

**Issue by rintoult** [AAFC-BICoE/dina-planning#73]
I was going to review Michele's comment about captions, so I went in to see how it looks. The stored object link seems to be getting hung up switching between two addresses.

http://dina-ui-template-dinaui.apps.biodiversity.agr.gc.ca/object-store/object/list

and

http://dina-ui-template-dinaui.apps.biodiversity.agr.gc.ca/object-store/object/list#state=26b19d5f-c812-404a-991e-bfcd19568448&session_state=7b460148-a4e8-40c6-958b-e6155a7ee54f&code=0932bd2a-0c51-4814-97fa-c9a6a683deee.7b460148-a4e8-40c6-958b-e6155a7ee54f.fe3ef8c1-e615-4528-960b-e86b3102c7c0

With a blank screen showing below the header. 

Using Chrome.

Tara

**Comment by Jkeyuk** [comment]
This seems consistent with a network issue reaching the server.

Was this done through a vpn connection? I know they can sometime lag or disconnect every now and again. Or is this something you experience on a consistent basis?

**Comment by rintoult** [comment]
I am on VPN and this is the first time I have encountered this.

Tara

**Comment by Jkeyuk** [comment]
Thanks for the update! 

Is the issue still on going for you, or are able to access the objects now?

**Comment by rintoult** [comment]
Still happening.

**Comment by Jkeyuk** [comment]
okay thanks we will definitely have to look into this.

**Comment by Jkeyuk** [comment]
So we have had a few developers, trying to re create any issues with no luck.

There is an idea going around that there could be a cookie/cache issue. 

It might be possible access objects after clearing your cookies or possibly re logging in.

If that helps let us know!

**Comment by rintoult** [comment]
That worked, of course I had to look up how to clear a cache in chrome. 

Put it into the usermanual in case it will always be necessary..............

**Comment by Jkeyuk** [comment]
Thanks for the update.

That helps narrow down the issue a bit. Ideally we will in a place will that will never be necessary, but having that information in the manual will be helpful.
