### ISSUE TITLE
Filter records by Metadata Created By IS <none> causes 'crash'

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#79]
In the Object Store, if I filter the records by Metadata Created By IS <none> and hit the Filter List Button, this causes some kind of 'crash' in DINA. What I mean by 'crash' is that the page goes blank and the search bar of my web browser flashes between: 
http://dina-ui-template-dinaui.apps.biodiversity.agr.gc.ca/object-store/object/list
AND
http://dina-ui-template-dinaui.apps.biodiversity.agr.gc.ca/object-store/object/list#state=fd24e7e8-f982-410a-b7a3-b8f35b03ee53&session_state=ac45457a-cdde-4985-9e4e-98f1a97232c9&code=1768b6aa-7cda-4196-8ea9-c670faf3a861.ac45457a-cdde-4985-9e4e-98f1a97232c9.fe3ef8c1-e615-4528-960b-e86b3102c7c0
I can return to the DINA home page but I cannot access the Object Store again until I clear my browser data.

Once my browser data has been cleared, I can log into DINA again and access the Object Store again.

Please fix this so that we can use <none> to search for no person in the Metadata Created By field.

**Comment by michellelocke** [comment]
* To clarify, my search bar of my browser flashes between the two strings listed above but the page displayed remains blank and doesn't change.

**Comment by cgendreau** [comment]
This is now resolved

**Comment by michellelocke** [comment]
Yes, I seems to be fixed. I am not having that problem any more.
