### ISSUE TITLE
Pre-select Uploaded By

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#8]
When uploading an object Uploaded By should be pre-selected with the current user.

**Comment by Jkeyuk** [comment]
I was able to verify this was working on the deployment server.

**Comment by hacole01** [comment]
should this be editable? seems strange that anyone uploading would be able to say the upload was done by someone else? Has that been communicated as a requirement? Else seems strange to be able to select/change anyone other than logged in user?

**Comment by cgendreau** [comment]
The text will be changed since here it's referring to the person who creates the metadata. The logged in user who uploaded the data is in another field that it is not displayed at the moment (since it can be done by a script for example)

**Comment by hacole01** [comment]
In this case, is it possible for the creator of metadata to be anyone other than the user doing the upload?
It is difficult to evaluate the interface when the field headers don't accurately represent the actual data/info in the fields.

**Comment by cgendreau** [comment]
Yes it can be a different user when for example a script is used but I don't think it can be different when the UI is used.

**Comment by cgendreau** [comment]
I will put this ticket to In Progress until the field can't be changed from the interface.
