### ISSUE TITLE
edit permissions in different groups

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#85]
today when i was testing upload to multiple groups. I tried some edits.

I found that I could edit data in the AAFC group that had been uploaded by other people. It is not clear to me how those permissions are managed.

I don't think we can assume that someone who should have upload/view rights to a group should also have full edit-rights, at least not by default.

I think it would be effective for the permissions to be explained to collection managers, then discussed.

**Comment by cgendreau** [comment]
You are `staff` in this group (so you can upload) which means you can also edit. Current permissions are simplified but this is working as intended for the moment. Documentation for collection manager is indeed not done yet and of course it could be refined but keeping it simple is always a win.

**Comment by rintoult** [comment]
This relates to my post #83

**Comment by heathercole** [comment]
for this issue and #83 it would be great if we could be provided a description of the intended end-point functionality, describing the different user-types and permissions. I think if we were provided that, and could verify it meets requirements, then would be easy to not get hung-up on the interim functionality.

**Comment by cgendreau** [comment]
defined in https://github.com/AAFC-BICoE/dina-planning/blob/master/docs/UserManual.md
