### ISSUE TITLE
best practices for metadata associated with the end-product media module

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#87]
I understand that while the media module and collection's management module for data records are being built that there are some interim solutions in place. 

I just wanted to document that when most of the development work is done, the media module should only be maintaining data pertaining to the media objects (not specimen data). Data associated with specimens (eg. taxonomy/geography, etc) can change, and unless there are tools in place to be sure that data is updated everywhere, it is much more simple to have it maintained in the data record, not with the related media objects. (note that view 'attributes' such as dorsal/ventral relate to the media object).

This also relates to relevant copyright and licensing, as the same rules don't necessarily always apply to the media object and the subject of the media.

GIVEN I have accessed DINA as collections' data manager

WHEN objects are added to and stored in the media server

THEN metadata associated to the objects should be restricted to data about the media object (not the subject of the media). Eg. the image file, not the specimen shown in the image.

AND data relating to the subject (eg. specimen/accession) should be maintained with the data record (not media object).

**Comment by jmacklin** [comment]
This was the original understanding about functionality required for the Multimedia Module and this has not changed.

**Comment by heathercole** [comment]
great, the more details that are provided about the intended-end-product, the more we understand and can review, without getting bogged down by interim functionality.
