### ISSUE TITLE
"is publicly releasable" field needs to be tied to 'flags' from the data/management module

### ISSUE THREAD

**Issue by heathercole** [AAFC-BICoE/dina-planning#89]
I think this is probably understood, but thought I would document also.

GIVEN I have accessed DINA as collection's data manager

WHEN a collection manager 'flags' a accession/specimen record in the database (eg. because restricted/CITES/redlisted species)

THEN the "is publicly releasable" field for associated media objects must also be updated/reviewed

AND the visibility of the object on the portal may need to change

**Comment by cgendreau** [comment]
The is done but in reverse order. You set the specimen as not publicly releasable and you record the reason.
