### ISSUE TITLE
Automatically set the name of Collector Group based on the selected agents

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#93]
GIVEN I have accessed DINA as a user

WHEN I create a new Collector Group

THEN the system automatically set the name of the group based on the selected agents

**Comment by cgendreau** [comment]
For example `M.M. Locke, O. Lonsdale & J.H. Skevington` .

The main blocker here is that the name used here is not available in the agent module and cannot be automatically generated since the middle is missing.

**Comment by heathercole** [comment]
was just writing you about this! I think a good idea, relates to #98 to clarify what data fields would be used, as current agent system just inputs 'display name'

**Comment by cgendreau** [comment]
Closing for now, we will reopen if required later
